#naval
province = { id =	433	naval_base = { size =	3	current_size = 	3	} } # Siracuse - Sicilian Gap - Italy
province = { 
	id =	1963	
	naval_base = { size =	8	current_size = 	8	}
	air_base = { size =	8	current_size = 	8	} 
} #wilmington
province = {
	id =	2050
	naval_base = { size =	3	current_size = 	3	}
	air_base = { size =	3	current_size = 	3	}
} # Buenos Aires
province = {
	id =	1944
	naval_base = { size =	6	current_size = 	6	}
	air_base = { size =	6	current_size = 	6	}
} # Mobile - Alabama - Southeast US
province = { id =	1986	naval_base = { size =	3	current_size = 	3	} } # Barranquilla - Panaman Ridge - Grand Colombia
province = { id =	2071	naval_base = { size =	3	current_size = 	3	} } # Recife
province = { id =	2052	naval_base = { size =	3	current_size = 	3	} } # Montevideo - La Plata - Rio de la Plata
#province = { 
#	id =	736	
#	naval_base = { size =	5	current_size = 	5	}
#	air_base = { size =	5	current_size = 	5	} 
#} #Bougie

province = {
	id = 1781   
	anti_air = 1 
	naval_base = { size = 4 current_size = 4 } 
} # Port-au-Prince - Hispaniola - Caribbean
province = { 
	id =	1545	
	naval_base = { size =	6	current_size = 	6	} 
	air_base = { size =	6	current_size = 	6	} 
} #Sapporo
#province = { 
#	id =	1549	
#	naval_base = { size =	5	current_size = 	5	}
#	air_base = { size =	5	current_size = 	5	} 
#} #Sendai
province = { 
	id =	1198	
	naval_base = { size =	5	current_size = 	5	}
	air_base = { size =	5	current_size = 	5	} 
} #Butehaqi
province = { 
	id =	1518	
	naval_base = { size =	8	current_size = 	8	}
	air_base = { size =	8	current_size = 	8	} 
} #Ahmedabad
province = { 
	id =	1657	
	naval_base = { size =	1	current_size = 	1	}
	air_base = { size =	1	current_size = 	1	} 
} #Makassar
province = { id =	1596	naval_base = { size =	1	current_size = 	1	} } #Hollandia
province = { id =	1587	naval_base = { size =	1	current_size = 	1	} } #Bougainville
province = { id = 1590   # Lunga
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 }
province = { id =	1990	naval_base = { size =	3	current_size = 	3	} } #Cucuta
province = {
	id =	1423	
	naval_base = { size =	6	current_size = 	6	}
	air_base = { size =	6	current_size = 	6	} 
} #Bangkok
province = { 
	id =	1636	
	naval_base = { size =	4	current_size = 	4	}
	air_base = { size =	4	current_size = 	4	} 
} #Palembang
province = {
	id =	1653
	naval_base = { size =	4	current_size = 	4	}
	air_base = { size =	4	current_size = 	4	}
} # Soerabaja - East Java - Indonesia
province = { 
	id =	1346	
	naval_base = { size =	10	current_size = 	10	}
	air_base = { size =	10	current_size = 	10	} 
} #Ningbo
province = {
	id =	1369
	naval_base = { size =	10	current_size = 	10	}
	air_base = { size =	6	current_size = 	6	}
} # Guangzhou - Guangdong - China
#province = { id =	1038	naval_base = { size =	2	current_size = 	2	} } #Doha
province = { 
	id =	1241	
	naval_base = { size =	6	current_size = 	6	}
	air_base = { size =	6	current_size = 	6	} 
} #Tianjin

###airbases
province = { id =	1991	air_base = { size =	8	current_size = 	8	} } #santa fe de bogota
province = { id = 	187	air_base = { size = 	7	current_size = 7	} } #Linz
#province = { id =	432	air_base = { size =	3	current_size = 	3	} } #Catania
#province = { id =	1715	air_base = { size =	3	current_size = 	3	} }
province = { id =	1882	air_base = { size =	10	current_size = 	10	} } #Bend
#province = { id =	1883	air_base = { size =	6	current_size = 	6	} }
province = { id = 1002   # Tamatave - Madagascar - Madagascar
   anti_air = 1 
   naval_base = { size = 3 current_size = 3 } 
 }
province = { id =	1050	air_base = { size =	1	current_size = 	1	} } #sanaa
#province = { id =	1051	air_base = { size =	1	current_size = 	1	} }
#province = { id =	1694	air_base = { size =	3	current_size = 	3	} } # Collie - Perth - Australia
#province = { id =	1616	air_base = { size =	3	current_size = 	3	} }


province = {
	id =	1542
	air_base = { size =	2	current_size = 	2	}
	naval_base = { size =	2	current_size = 	2	}
	supplypool = 100
} #toyohara

province =
{ id         = 1052
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Mascate

province =
{ id         = 2142
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 2141 supplypool = 1000 } # Juneau
# Province =
# { id       = 592
  # anti_air = 1
  # air_base = { size = 4 current_size = 4 }
# }            # Plattsburgh
province =
{ id       = 1787
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -2
}            # Concord
 province = { id = 1785   #  Lewiston - Maine - Northeast US
   ic = -3 }
 province = { id = 1788   #  Hartford - Massachussets - Northeast US
   ic = -6 }
province =
{ id         = 1789
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -4
}              # Boston

 province = { id = 1791   #  Buffalo - New York - Northeast US
   ic = -11 }
 province = { id = 1792   #  Syracuse - New York - Northeast US
   ic = -2 }
 province = { id = 1793   #  Albany - New York - Northeast US
   ic = -5 }

province =
{ id         = 1795
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -11
}              # New York
province = { 
	id = 1797
	ic = -3 
	air_base   = { size = 10 current_size = 10 }
	Naval_base = { size = 10 current_size = 10 }
}   #  Newark - New Jersey - Northeast US
 province = { id = 1801   #  Harrisburg - Pennsylvania - Northeast US
   ic = -5 }
# province =
# { id         = 1809
  # anti_air   = 4
  # air_base   = { size = 10 current_size = 10 }
  # Naval_base = { size = 10 current_size = 10 }
  # ic = -1
# }              # Washington D.C.
province = {
	id = 1805
	anti_air = 2
	ic = -11
} # Philadelphia
province =
{ id       = 1806
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -5
}            # Pittsburgh
 province = { id = 1808   #  Baltimore - Maryland_Delaware - Northeast US
   ic = -11 }
province =
{ id       = 1845
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -9
}            # Detroit
province =
{ id       = 1832
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  ic = -2
}            # Chicago
province =
{ id       = 1839
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -4
}            # Milwaukee
province =
{ id         = 1812
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -2
}   #Norfolk

 province = { id = 1800   #  Binghampton
   ic = -2 }
  province = { id = 1813   #  Richmond - Virginia - Northeast US
   ic = -3 }
 province = { id = 1821   #  Columbus - Ohio - Northeast US
   ic = -5 }
 province = { id = 1823   #  Cincinnati - Ohio - Northeast US
   ic = -9 }
 province = { id = 1824   #  Erie - Ohio - Northeast US
   ic = -5 }
 province = { id = 1825   #  Cleveland - Ohio - Northeast US
   ic = -12 }
 province = { id = 1826   #  Fort Wayne - Indiana - Northeast US
   ic = -5 }
 province = { id = 1828   #  Indianapolis - Indiana - Northeast US
   ic = -3 }
 province = { id = 1832   #  Chicago - Illinois - Midwest US
   ic = -7 }
 province = { id = 1839   #  Milwaukee - Wisconsin - Midwest US
   ic = -4 }
 province = { id = 1844   #  Flint - Michigan - Midwest US
   ic = -7 }
 province = { id = 1847   #  Minneapolis - Minnesota - Midwest US
   ic = -2 }
province =
{ id         = 1867
  anti_air   = 1
  air_base   = { size = 3 current_size = 3 }
  Naval_base = { size = 5 current_size = 5 }
}
Province =
{ id       = 1962
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 1819
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 1960
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charleston
Province =
{ id       = 1952
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id         = 1953
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = 1
}              # Miami
province = { id = 1794 ic = -1 } #watertown
province = { id = 1798 ic = -1 } #warren
province = { id = 1820 ic = -2 } #lexington
province = { id = 1822 ic = -4 } #toledo
province = { id = 1827 ic = -2 } #evansville
province = { id = 1830 ic = -3 } #Decatur
province = { id = 1834 ic = -3 } #Saint Joseph
province = { id = 1859 ic = -1 } #Lincoln
province = { id = 1848 ic = -2 } #Superior
province = { id = 1849 ic = -3 } #Green Bay
province = { id = 1908 ic = -3 } #Colorado Springs
province = { id = 1914 ic = -5 } #kansas city
province = { id = 1917 ic = -1 } #fort smith
province = { id = 1929 ic = -1 } #Monroe
province = { id = 1942 ic = -4 } #Knoxville
province = { id = 1943 ic = -2 } #Nashville
province = { id = 1945 ic = -2 } #Gadsden
province = { id = 1946 ic = -3 } #Birmingham  Al
province = { id = 1947 ic = -1 } #Montgomery
province = { id = 1948 ic = -2 } #Tampa
province = { id = 1949 ic = -2 } #Orlando
province = { id = 1957 ic = -2 } #Columbia
province = { id = 1958 ic = -1 } #Greenville
province = { id = 1959 ic = -2 } #Augusta
province = { id = 1961 ic = -2 } #Raleigh
province = { id = 1796 ic = -2 } #Providence
province = { id = 2134 ic = -1 } #glace bay
province = { id = 2124 ic = -1 } #rimouski
province = { id = 1739 supplypool = 100 } # Midway Island
province =
{ id         = 1734
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
  oilpool = 500
}              # Pearl Harbour
province =
{ id       = 1954
  ic = -4
}            # Macon
province =
{ id       = 1955
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -3
}            # Atlanta
Province =
{ id       = 1940
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -10
}            # Memphis
# Province =
# { id       = 678
  # anti_air = 1
  # air_base = { size = 4 current_size = 4 }
# }            # Biloxi
province =
{ id       = 1918
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -1
}            # Little Rock
 province = { id = 1931   #  New Orleans - Louisiana - Southcentral US
   ic = -6 }
province =
{ id       = 1833
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -9
}            # St. Louis
province =
{ id       = 1836
  ic = -1
} #springfield
province =
{ id       = 1838
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -1
}            # Des Moines
province =
{ id       = 1847
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
# province =
# { id       = 698
  # anti_air = 1
  # air_base = { size = 4 current_size = 4 }
# }            # Bismarck
province =
{ id       = 1908
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -1
}            # Denver
Province =
{ id       = 1913
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -1
}            # Oklahoma City
province =
{ id       = 1928
  anti_air = 1
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 }
}            # Houston
# province =
# { id       = 865
  # anti_air = 1
  # air_base = { size = 4 current_size = 4 }
  # naval_base = { size = 4 current_size = 4 }
# }            # Tierra del Fuego
Province =
{ id       = 1906
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 1900
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 1896
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  ic = -3
}            # Salt Lake City
Province =
{ id         = 1922
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -1
}              # Corpus Christi
province =
{ id         = 1886
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -2
}              # San Diego
province =
{ id         = 1887
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
  ic = -3
}              # Los Angeles
province =
{ id       = 1888
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 1889
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 1874
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  ic = -3
}              # Seattle
province =
{ id       = 1878
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -3
}            # Portland
province =
{ id       = 1860
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic = -2
}            # Omaha
province =
{ id       = 1912
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province = { id = 2174   # Attu Island - Alaskan Archipelago - Alaska
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 }
province =
{ id         = 1683
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Guam
#province = { id = 1756 supplypool = 50 } # Samoa
province = { id = 1745 supplypool = 1 } # Jarvis Island
province = { id = 1747 supplypool = 50 } # Palmyra
#province = { id = 1766 supplypool = 1 } # Johnson Island
province =
{ id         = 1673
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Wake Island


province =
{ id         = 1726
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 2 current_size = 2 }
  anti_air   = 2
}              # Rabaul
province =
{ id       = 1602
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # Lae

### Australasia

province =
{ id         = 1607
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 1
  supplypool = 50
}              # Port Moresby
province =
{ id         = 1697
  anti_air   = 5
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  ic         = 1
}              # Darwin
province =
{ id          = 1690
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 1
}               # Perth
#province = { id = 1715 anti_air = 1 } # Port Augusta
province =
{ id          = 1704
  anti_air    = 4
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 1
  ic          = 3
}               # Brisbane
#province = { id = 1724 anti_air = 3 } # Wentworth
province =
{ id          = 1705
  anti_air    = 4
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 2
  ic          = 2
}               # Sydney
province = { id = 1707   # Canberra - Sydney - Australia
   anti_air = 2
   naval_base = { size = 10 current_size = 10 }
   air_base = { size = 10 current_size = 10 }
   coastalfort = 2
 }
province = { id = 1708 landfort = 0 coastalfort = 1 anti_air = 3 } # Melbourne
province = { id = 1712 anti_air = 2 } # Adelaide

province = { id = 1721   # Wellington - New Zealand - Australia
   anti_air = 2
   naval_base = { size = 5 current_size = 5 }
   air_base = { size = 3 current_size = 3 }
 }
province = { id =	1722	naval_base = { size =	3	current_size = 	3	} } #Christchurch
province = { 
	id =	1710	
	naval_base = { size =	1	current_size = 	1	}
	air_base = { size =	1	current_size = 	1	} 
} #Hobart
province = { 
	id =	1701	
	naval_base = { size =	5	current_size = 	5	}
	air_base = { size =	5	current_size = 	5	} 
} #Cairns
province = { 
	id =	1699	
	naval_base = { size =	5	current_size = 	5	} 
	air_base = { size =	5	current_size = 	5	}
} #Townsville

### Austria

# province =
# { id         = 403
  # anti_air   = 2
  # air_base = { size = 5 current_size = 5 }
  # naval_base = { size = 10 current_size = 10 }
  # landfort = 2
# } #Capodistria
province =
{ id         = 406
  anti_air   = 2
  coastalfort = 1
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 8 current_size = 8 }
} #Pola
province =
{ id       = 189
  anti_air = 1
}            # Innsbruck
province =
{ id       = 401
  landfort = 2
}            # Trento
province =
{ id       = 402
  anti_air = 1
  landfort = 3
}            # Bolzano
province = { id = 191 anti_air = 1 landfort = 2 } # Klagenfurt
province =
{
	id = 405 #udine
	landfort = 3
	anti_air = 1
}
province =
{ id       = 195
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}            # Vienna

province =
{ id         = 1328
  naval_base = { size = 10 current_size = 10 }
}              # Qingdao
province =
{ id         = 1338
  naval_base = { size = 10 current_size = 10 }
}              # Shanghai
province =
{ id       = 1345
  air_base = { size = 10 current_size = 10 }
}            # Hangzhou
province =
{ id       = 1358
  air_base = { size = 1 current_size = 1 }
}            # Fuzhou
province =
{ id       = 1352
  air_base = { size = 10 current_size = 10 }
}            # Nanchang
province =
{ id       = 1297
  air_base = { size = 3 current_size = 3 }
}            # Chengdu

province =
{ id         = 383
  anti_air   = 2
} #Mytilene

province =
{ id         = 1765
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 4 current_size = 4 }
  anti_air   = 2
}              # Puerto Rico

province =
{ id         = 1
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
  anti_air   = 2
}              # Reykjavik



province =
{ id       = 520
  air_base = { size = 10 current_size = 10 }
}            # Oulu
province =
{ id          = 524
  coastalfort = 1
  anti_air    = 2
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 10 current_size = 10 }
}               # Turku
province =
{ id          = 525
  coastalfort = 1
  anti_air    = 3
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 8 current_size = 8 }
}               # Helsinki
province =
{ id       = 527
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Tampere
#province = { id = 531 landfort = 3 anti_air = 3 } # Viipuri
province = { id = 539 landfort = 2 anti_air = 2 } #petrozavodsk
province = { id = 541 landfort = 2 anti_air = 2 } #Belomorsk
province =
{ id         = 37
  anti_air   = 3
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 10 current_size = 10 }
}              # Brest
province = { id = 57 anti_air = 2 } # Nantes
province =
{ id         = 43
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Cherbourg
province = { id = 44 anti_air = 1 } # Caen
province =
{ id         = 51
  naval_base = { size = 3 current_size = 3 }
}              # Dunkerque
province =
{ id       = 52
  air_base = { size = 10 current_size = 10 }
  anti_air = 1
}            # Lille
province =
{ id       = 55
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}            # Paris
# province =
# { id       = 59
  # air_base = { size = 10 current_size = 10 }
# }            # Cholet
province =
{ id       = 63
  air_base = { size = 10 current_size = 10 }
}            # Auxerre
province =
{ id       = 121
  landfort = 2 #3
}  #maastricht
province =
{ id       = 119
  landfort = 2 #3
}  #arnhem
province =
{ id       = 120
  landfort = 2 #3
}  #nijmegen
province =
{ id       = 124
  landfort = 1 #3
}  #Groningen
province = { 
	id = 129 
	landfort = 2 
} # Koblenz
province =
{ id       = 54
  anti_air  = 2
  air_base   = { size = 10 current_size = 10 }
}  #troyes
province =
{ id       = 113
  anti_air  = 2
  air_base   = { size = 10 current_size = 10 }
}  #namur
province = { 
	id = 111 
	landfort = 1 
} # Arlon
province = { id = 110 landfort = 3 } # Eupen
province = { 
id = 109 
anti_air = 2 
landfort = 4 #5 
} # luxembourg
province = { id = 108 landfort = 3 } # #liege
province = { id = 107 landfort = 1 } # Strassburg
province = { id = 106 landfort = 4 } # Nancy
province = { id = 105 anti_air = 2 landfort = 3 } # Colmar
province =
{ id       = 104
  air_base = { size = 10 current_size = 10 }
  landfort = 3
  anti_air = 2
}            # Metz
province = { id = 100 landfort = 3 } # Verdun
#province = { id = 98 landfort = 1 } # Pontarlier
province = { id = 97 landfort = 3 } # Belfort
province = { id = 96 landfort = 3 } # Longwy
province = { id = 95 landfort = 3 } # Chaumont
province = { id = 74 anti_air = 1 } # Vichy
province =
{ id         = 68
  anti_air   = 4
  landfort = 1
  coastalfort = 2
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}              # Bordeaux
province =
{ id       = 77
  air_base = { size = 10 current_size = 10 }
}            # Toulouse
province = {
	id = 82
	landfort = 3
	coastalfort = 2
} # montpellier
province =
{ id         = 89
  ic         = 1
  anti_air   = 3
  coastalfort = 1
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 8 current_size = 8 }
}              # Marseille
province =
{ id         = 747
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Tunis
province =
{ id         = 727
  anti_air   = 4
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 5 current_size = 5 }
}              # Algiers
province =
{ id         = 728
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Oran
province =
{ id         = 718
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Casablanca
province = {
	id =	715
	naval_base = { size =	2	current_size = 	2	}
	air_base = { size =	2	current_size = 	2	}
	#supplypool = 500
	#oilpool = 10
}			# Tangier
province =
{ id         = 978
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Dakar
province =
{ id       = 962
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Abidjan
province = { id = 833 naval_base = { size = 1 current_size = 1 } } # Djibouti
province =
{ id         = 1395
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Hanoi
province =
{ id         = 1399
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Saigon

province =
{ id         = 969
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # Monrovia
province =
{ id       = 145
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Essen
province = { 
	id = 131 
	landfort = 1 #3
} # Cologne
province = { 
	id = 126 
	landfort = 1 #3
} # Aachen
province = { id = 127 landfort = 1 } # Saarbrucken
province = { id = 128 landfort = 1 } # Trier
province =
{ 
	id         = 147
	anti_air   = 2
	landfort   = 1 #3
	coastalfort = 1 #2
	air_base = { size = 4 current_size = 4 }
	naval_base = { size = 10 current_size = 10 }
}              # Wilhelmshafen
#province =
#{ id         = 148
#  anti_air   = 2
#  air_base   = { size = 4 current_size = 4 }
#}              # Bremen
province =
{ id         = 141
  landfort   = 1 #3
}              # Münster
province = {
	id = 173
	anti_air = 2
	air_base = { size = 4 current_size = 4 }
} # Dresden
province =
{ id         = 152
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Kiel
province =
{ id         = 153
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 8 current_size = 8 }
}              # Rostock
province = {
	id =	181
	air_base = { size = 6 current_size = 6 }
	naval_base = { size = 8 current_size = 8 }
} #danzig
#province = {
#	id =	261
#	naval_base = { size = 2 current_size = 2 }
#} #klaipeda
province =
{ id         = 184
  anti_air   = 4
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 2 current_size = 2 }
}              # Königsberg
province =
{ id       = 163
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Berlin
province = { id = 170 anti_air = 1 } # Leipzig
province = { id = 177 anti_air = 1 } # Nuremberg
province =
{ id       = 138
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Frankfurt-am-Main
province =
{ id       = 134
  anti_air = 2
  air_base = { size = 5 current_size = 5 }
}            # Stuttgart
province =
{ id       = 179
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Munich
province =
{ id       = 207
  anti_air = 1
  air_base = { size =	8	current_size = 	8	}
}            # Prague
province =
{ id       = 284
  anti_air = 1
  air_base = { size =	8	current_size = 	8	}
}            # Budapest

province =
{ id         = 2156
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 1 current_size = 1 }
} #Visby

province =
{ id         = 1988
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}              # Maracaibo
province = { id = 1993 anti_air = 2 } # Caracas


province =
{ id         = 441
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # La Coruña
province =
{ id       = 460
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Madrid
province =
{ id         = 467
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
}            #Cordoba
province =
{ id         = 447
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # Seville
province =
{ id         = 464
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 2 current_size = 2 }
}              # València
province =
{ id         = 436
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Tarragona
province =
{ id         = 475
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool = 100
}              # Mallorca/Baleares
province =
{ id         = 990
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
}              # Gran Canaria
province =
{ id         = 988
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Villa Cisneros

province =
{ id         = 31
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Cork

province =
{ id         = 36
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Belfast

province =
{ id         = 34
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Dublin

province = { id = 2057 anti_air = 1 } # Curitiba
province =
{ id         = 2058
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Pôrto Alegre
province = { id = 2067 anti_air = 2 } # Goiania
province =
{ id         = 2023
  anti_air   = 2
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}  #santiago de chile
province =
{ id         = 2075
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Rio de Janeiro
province =
{ id         = 2059
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # São Paulo

province =
{ id         = 1547
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Akita
province =
{ id         = 1552
  ic         = 7
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Tokyo
province =
{ id         = 1557
  ic         = 3
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Nagoya
province =
{ id         = 1556
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Kanazawa
province =
{ id         = 1553
  ic         = 2
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Osaka
province =
{ id         = 1554
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Hiroshima
province =
{ id         = 1561
  ic         = 3
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Kagoshima
province =
{ id         = 1560
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # nagasaki

province = { id = 1563   # Southern Okinawa - Ryukyusland - Japan
   anti_air = 2
   air_base = { size = 6 current_size = 6 }
   naval_base = { size = 6 current_size = 6 }
   supplypool = 100
 }
province = { id = 1661   # Iwo Jima - Bonin - Asian Pacific
	air_base = { size = 4 current_size = 4 }
	naval_base = { size = 4 current_size = 4 }
	supplypool = 100
}

province = { id = 1672   # Minami Torishima
   air_base = { size = 1 current_size = 1 }
   naval_base = { size = 1 current_size = 1 }
   supplypool = 100
}

province =
{ id         = 1219
  anti_air   = 4
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 7 current_size = 7 }
  supplypool = 500
  oilpool = 100
}              # port arthur
province = { id = 1245 supplypool = 1000 oilpool = 100 } # Tangshan
# province =
# { id         = 1322
  # anti_air   = 2
  # air_base   = { size = 8 current_size = 8 }
  # naval_base = { size = 10 current_size = 10 }
  # supplypool = 1000
  # oilpool    = 100
# }              # Kaohsiung
province = {
	id = 1362
	anti_air = 2
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 8 current_size = 8 }
	supplypool = 100
} # Taipei Taiwan
# province =
# { id       = 1391
  # anti_air = 2
  # air_base = { size = 4 current_size = 4 }
# }            # Hyesan
province =
{ id       = 1310
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # Changde
province = { id = 1611 supplypool = 500 } # Iwo Jima
province =
{ id         = 1675
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
}              # Eniwetok
province = { id = 1677 anti_air = 3 } # Majuro
province =
{ id         = 1676
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 2000
}              # Kwajalein
province = { id = 1665 supplypool = 500 } # Ponape
province =
{ id         = 1667
  anti_air   = 5
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 500
}              # Truk
province = { id = 2478 anti_air = 3 supplypool = 500 } # Yap
province = { id = 1684 supplypool = 500 } # Rota
province = { id = 1685 anti_air = 3 supplypool = 500 } # Saipan
province = { id = 2476 anti_air = 2 } # Bonin Islands
province = { id = 2416 supplypool = 500 } # Marcus Island

province =
{ id       = 262
  air_base = { size = 2 current_size = 2 }
}            # Kaunas

# province =
# { id         = 1108
  # anti_air   = 2
  # naval_base = { size = 3 current_size = 3 }
  # air_base   = { size = 1 current_size = 1 }
# }              # Walvis Bay
province =
{ id         = 880
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Cape Town
province = { id = 1117 anti_air = 1 } # Port Elisabeth
province =
{ id         = 872
  anti_air   = 3
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Durban
province = { id = 876 anti_air = 3 } # Johannesburg


province =
{ id         = 396
  landfort   = 2
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Genoa
province =
{ id         = 408
  landfort   = 2
  anti_air   = 3
}              # Parma
province =
{ id       = 393
  landfort   = 2
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
} #Brescia
province =
{ id       = 407
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Milan
province =
{ id         = 400
  anti_air   = 2
  landfort   = 5
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 10 current_size = 10 }
}              # Venice
province = { id = 411 landfort = 2 anti_air = 1 } # Bologna
province = {
	id = 410
	landfort = 2
	anti_air = 1
	#naval_base = { size = 5 current_size = 5 }
	#air_base   = { size = 5 current_size = 5 }
} # Florence
province =
{ id       = 419
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  #naval_base = { size = 2 current_size = 2 }
}            # Rome
province =
{ id       = 421
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}            # Naples
province =
{ id         = 422
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Taranto
province =
{ id         = 430
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Palermo
province = { id = 91 landfort = 1 } # chambery
province = { id = 398 landfort = 1 anti_air = 2 } # Turin
province =
{ id         = 434
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Cagliari
province =
{ id         = 765
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  landfort   = 3
}              # Tobruk
province =
{ id         = 761
  anti_air   = 1
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 4 current_size = 4 }
}              # Benghazi
province =
{ id         = 750
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 3 current_size = 3 }
}              # Tripoli
province =
{ id         = 815
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # Massawa

province = {
	id = 836   # Mogadishu - Somalia - Horn of Africa
	anti_air = 1
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
}

province =
{ id         = 892
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
} #lobito


province = { id = 1975 anti_air = 1 } # Monterrey
province = { id = 1982 anti_air = 1 } # Guadalajara
province = {
	id = 1974
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
} # Mexico City
province =
{ id         = 1972
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Acapulco


province =
{ id         = 1565
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 2 current_size = 2 }
}              # Manila
province =
{ id         = 1569
  anti_air   = 4
  air_base   = { size = 5 current_size = 5 }
  Naval_base = { size = 2 current_size = 2 }
}              # Olongapo


province =
{ id         = 1966
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
} #Merida

province =
{ id         = 888
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 2 current_size = 2 }
} #Lubango


province =
{ id         = 307
  anti_air   = 2
  landfort = 2
  coastalfort = 1
}              # Dobrich
province =
{ id         = 310
  anti_air   = 1
  #landfort = 1
  coastalfort = 1
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
  ic         = 1
}              # Constantza
province =
{ id       = 316
  anti_air = 2
  landfort = 1
  air_base = { size = 5 current_size = 5 }
}            # Bucharest
province = { id = 311 anti_air = 3 } # Ploesti
province = { id = 306 anti_air = 1 } # Ismail
province = { id = 312 landfort = 1 } # tirmi severom
province = { id = 315 landfort = 1 } # craiova
province = { id = 308 landfort = 1 } # giurgiu

province =
{ id         = 535
  anti_air   = 4
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 3 current_size = 3 }
}              # Murmansk
province =
{ id         = 542
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 4 current_size = 4 }
}              # Archangelsk
province =
{ id          = 663
  air_base    = { size = 10 current_size = 10 }
  landfort    = 2
  anti_air    = 2
}               # Stalingrad/Volgograd
province =
{ id          = 572
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  anti_air    = 4
}               # Moscow
province =
{ id       = 576
  air_base = { size = 3 current_size = 3 }
  anti_air = 1
}            # Kaluga
province =
{ id          = 553
  naval_base  = { size = 3 current_size = 3 }
  air_base    = { size = 3 current_size = 3 }
} #leningrad/odinholm
province =
{ id       = 564
  air_base = { size = 6 current_size = 6 }
}            # Opochka
province =
{ id       = 590
  air_base = { size = 2 current_size = 2 }
  anti_air = 2
}            # Vitebsk
province = { id = 589 anti_air = 3 } # Smolensk
province =
{ id       = 600
  air_base = { size = 8 current_size = 8 }
}            # Mogilev
province =
{ id       = 626
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Odessa
province =
{ id       = 617
  air_base = { size = 8 current_size = 8 }
  anti_air = 3
}            # Kiev
province = { id = 630 anti_air = 2 } # Zaporozhye
province =
{ id       = 636
  air_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # Kharkov
province =
{ id          = 641
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 6 current_size = 6 }
  landfort    = 3
  coastalfort = 5
}               # Sevastopol
province =
{ id       = 644
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # Rostov
#province = { id = 263 anti_air = 1 } # Svoboda
province =
{ id       = 653
  air_base = { size = 2 current_size = 2 }
}            # Pavlovsk
province =
{ id       = 601
  air_base = { size = 2 current_size = 2 }
}            # Gomel
province = { id = 588 anti_air = 2 } # Bryansk
province =
{ id       = 1179
  air_base = { size = 1 current_size = 1 }
}            # Yakutsk
province =
{ id         = 625
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
}              # Ochakov
province =
{ id          = 1191
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 1
  coastalfort = 3
}               # Vladivostok
province =
{ id       = 1162
  air_base = { size = 3 current_size = 3 }
}            # Irkutsk
province = {
	id = 1523   # Gwalior - Rajastan - India
	anti_air = 1
	air_base = { size = 2 current_size = 2 }
}
province =
{ id         = 1186
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # Okhotsk
province =
{ id       = 1148
  air_base = { size = 2 current_size = 2 }
}            # Tomsk
province = {
	id = 1550   # Yokohama - Tohoku - Japan
	anti_air = 2
}
province =
{ id       = 1138
  air_base = { size = 1 current_size = 1 }
}            # Omsk
province =
{ id       = 1132
  air_base = { size = 1 current_size = 1 }
}            # Chelyabinsk
province =
{ id       = 664
  air_base = { size = 2 current_size = 2 }
}            # Naberezhnye Chelny
province =
{ id       = 668
  air_base = { size = 4 current_size = 4 }
}            # Kuybyshev
province =
{ id       = 669
  air_base = { size = 3 current_size = 3 }
}            # Saratov
province =
{ id       = 706
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Astrakhan
province =
{ id         = 708
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Kutaisi


province = {
	id = 2152
	landfort = 0
	coastalfort = 1
} # Malmö

province =
{ id          = 2153
  anti_air    = 2
  naval_base  = { size = 7 current_size = 7 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 0
  coastalfort = 3
}               # Göteborg
#province = { id = 99 landfort = 1 coastalfort = 0 } # Skövde
province =
{ id          = 2159
  anti_air    = 2
  naval_base  = { size = 7 current_size = 7 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 0
  coastalfort = 3
}               # Stockholm
province =
{ id          = 2166
  anti_air    = 2
  naval_base  = { size = 3 current_size = 3 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 3
  coastalfort = 0
}               # Luleå

#.#.# Switzerland

province = { id = 389   # Zurich - Switzerland - Switzerland
   landfort = 5
   anti_air = 3
}
province = { id = 390   # Lugano - Switzerland - Switzerland
   landfort = 4
   anti_air = 3
 }
province = { id = 391   # Geneva - Switzerland - Switzerland
   landfort = 5
   anti_air = 3
}
province ={ id = 392   # Bern - Switzerland - Switzerland
   anti_air = 5
   air_base = { size = 4 current_size = 4 }
   landfort = 5
 }

province =
{ id         = 1776
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base = { size = 2 current_size = 2 }
}              # Havana

province =
{ id         = 1782
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 100
}              # Jamaica

province =
{ id         = 2089
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Vancouver
province =
{ id       = 2106
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Winnipeg
province =
{ id         = 2132
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Halifax
province =
{ id         = 2130
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 4 current_size = 4 }
}              # Saint John
province =
{ id       = 2119
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Montréal
province =
{ id         = 2117
  anti_air   = 4
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Québec City
province =
{ id       = 2108
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Ottawa
province = { id = 2111 anti_air = 1 ic = -4 } # Toronto
province = { id = 2109 ic = -4 } # Hamilton
province =
{ id       = 2104
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Calgary


province =
{ id       = 1247
  air_base = { size = 5 current_size = 5 }
}            # Beiping
province =
{ id       = 1330
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Jinan

province =
{ id         = 5
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Scapa Flow
#province =
#{ id       = 11
#  anti_air = 2
#  air_base = { size = 4 current_size = 4 }
#}            # Glasgow
province =
{ id         = 18
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  #naval_base = { size = 10 current_size = 10 }
}              # Sheffield
#province =
#{ id         = 24
#  anti_air   = 4
#} #birmingham
province =
{ id         = 17
  anti_air   = 4
  #air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 8 current_size = 8 }
}              # Manchester
province =
{ id         = 25
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Norwich
province = {
	id = 19
	anti_air = 3
	air_base = { size = 4 current_size = 4 }
} # London
province =
{ id          = 26
  anti_air    = 5
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
}               # Dover
province =
{ id         = 27
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Portsmouth
province =
{ id         = 23
  anti_air   = 2
  #air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Plymouth

province =
{ id          = 348
  anti_air    = 2
  landfort    = 3
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 5 current_size = 5 }
}               # Gibraltar
province =
{ id         = 1773
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id       = 1758
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}
#province =
#{ id       = 652
#  anti_air = 1
#  air_base = { size = 4 current_size = 4 }
#}            # Andros
province =
{ id         = 2045
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 1999
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Paramaribo
province = { id = 900 anti_air = 2 landfort = 4 coastalfort = 1 } # Suez
province = {
	id = 791
	anti_air = 2
	naval_base = { size = 2 current_size = 2 }
} # Port Said
province = { id = 787 anti_air = 2 } # Cairo
province =
{ id         = 789
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Alexandria
province =
{ id         = 964
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  #oilpool    = 1000
  #supplypool = 2000
}              # Freetown
province =
{ id       = 956
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 929
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Lagos
province =
{ id       = 842
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 810
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1410
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1415
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1371
  anti_air    = 4
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 1
  oilpool     = 500
  supplypool  = 1000
}               # Hong Kong
province = {
	id = 1372
	naval_base = { size = 3 current_size = 3 }
	air_base = { size = 1 current_size = 1 }
} #Macao
province =
{ id          = 1367
  anti_air    = 1
  naval_base  = { size = 6 current_size = 6 }
}               # Naoming
province =
{ id          = 1432
  anti_air    = 6
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Singapore
province =
{ id       = 1447
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}            # Calcutta
#province =
#{ id       = 1467
#  anti_air = 1
#  air_base = { size = 4 current_size = 4 }
#}            # Indore
province =
{ id       = 1459
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province =
{ id         = 1533
  anti_air   = 1
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 5 current_size = 5 }
}              # Karachi
province =
{ id         = 1517
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  landfort = 3
}              # Bombay/Mumbai/Manuelopolis
province =
{ id       = 1497
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}            # Cochin
#province =
#{ id         = 1516
#  anti_air   = 1
#  air_base   = { size = 2 current_size = 2 }
#  naval_base = { size = 2 current_size = 2 }
#}              # Trincomalee
province =
{ id          = 1511
  anti_air    = 2
  air_base    = { size = 7 current_size = 7 }
  naval_base  = { size = 7 current_size = 7 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id       = 1624
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool  = 100
}            # Kuching
province =
{ id         = 1053
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # Aden
#province =
#{ id         = 1817
#  anti_air   = 2
#  air_base   = { size = 6 current_size = 6 }
#  naval_base = { size = 10 current_size = 10 }
#  oilpool    = 100
#  supplypool = 200
#}              # Diego Garcia Island
province =
{ id         = 599
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
}              # Minsk
province =
{
	id = 1647
	anti_air = 2
	naval_base = { size = 3 current_size = 3 }
	air_base = { size = 4 current_size = 4 }
}  #Batavia
province = { id = 258 anti_air = 1 } # Wilno
#province =
#{ id       = 211
#  air_base = { size = 3 current_size = 3 }
#  anti_air = 3
#}            # Lida
province =
{ id       = 238
  air_base = { size = 4 current_size = 4 }
}            # Stanislawow
#province = { id = 222 anti_air = 1 } # Torun
province = { id = 224 anti_air = 2 } # Poznan
province = { id = 235 anti_air = 2 } # Cracow
province =
{ id       = 223
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Lodz
province =
{ id       = 232
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # Warsaw
province =
{ id       = 247
  air_base = { size = 3 current_size = 3 }
}            # Brest Litovsk
province = { id = 252 anti_air = 1 } # Suwalki

province =
{ id       = 709
  anti_air = 2
  landfort = 1
  air_base = { size = 5 current_size = 5 }
}  #Tbilisi

province =
{ id       = 894
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
}  #matadi

province =
{ id       = 993
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}  #Ascension Island

province =
{ id       = 2240
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}  #st helena

province =
{ id       = 1124
  air_base = { size = 1 current_size = 1 }
}            # Ulaanbaatar

province =
{ id       = 1289
  air_base = { size = 1 current_size = 1 }
}  #Lhasa

# province =
# { id       = 1442
  # air_base = { size = 2 current_size = 2 }
# }

province =
{ id       = 504
  air_base = { size = 2 current_size = 2 }
}    #Alma-Ata

# province =
# { id       = 1101
  # air_base = { size = 2 current_size = 2 }
  # naval_base = { size = 2 current_size = 2 }
# }

province =
{ id       = 1421
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}  #Port Blair

province = {
	id =	2079
	naval_base = { size =	5	current_size = 	3	}
	air_base = { size = 5 current_size = 5 }
} #san salvador
province =
{ id         = 889
  anti_air   = 3
  landfort   = 1
  air_base   = { size = 5 current_size = 5 }
  Naval_base = { size = 5 current_size = 5 }
  supplypool = 100
}

province =
{ id         = 1400
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
} #Phnom Penh

province =
{ id         = 1401
  anti_air   = 1
  landfort   = 1
  air_base   = { size = 5 current_size = 5 }
} #Siem Reap

province = {
	id = 825   # Addis Abeba - North Ethiopia - Ethiopia
	anti_air = 1
	air_base = { size = 2 current_size = 2 }
}

### iberia

province = { 
	id =	461	
	naval_base = { size =	3	current_size = 	3	}
	air_base = { size =	3	current_size = 	3	} 
} #Castellon de la Plana
province = { 
	id =	440	
	naval_base = { size =	8	current_size = 	8	}
	air_base = { size =	8	current_size = 	8	}
} #Barcelona
province = {
	id = 472
	air_base   = { size = 7 current_size = 7 }
	naval_base = { size = 10 current_size = 10 }
} #huelva
province = {
	id = 437
	landfort = 1
} #gerona
province = {
	id = 438
	landfort = 1
} #huesca
province = {
	id = 439
	landfort = 1
} #lerida
province = {
	id = 443
	landfort = 2
} #bilbao
province = {
	id = 446
	landfort = 2
} #pamplona

province = {
	id = 476   # Lisbon - Portugal - Portugal
	anti_air = 2
	naval_base = { size = 8 current_size = 8 }
	air_base = { size = 8 current_size = 8 }
}

#morocco
province = {
	id = 995
	anti_air = 2
	naval_base = { size = 3 current_size = 3 }
	air_base = { size = 4 current_size = 4 }
} # The Azores

province = {
	id = 2016
	anti_air = 2
	naval_base = { size = 3 current_size = 3 }
	air_base = { size = 4 current_size = 4 }
} # Lima

province = {
	id = 2040
	anti_air = 2
	naval_base = { size = 5 current_size = 5 }
	air_base = { size = 4 current_size = 4 }
} # Santiago de Guayaquil

province = {
	id = 950
	anti_air = 1
	ic = 1
	naval_base = { size = 3 current_size = 3 }
	air_base = { size = 4 current_size = 4 }
} # Lome

province = {
	id = 2070
	naval_base = { size = 5 current_size = 5 }
	air_base = { size = 4 current_size = 4 }
} # Natal

### Union of Rome

province = { id =	321	air_base = { size =	2	current_size = 	2	} } #Sofia
province = { 
	id =	373	
	naval_base = { size =	2	current_size = 	2	}
	air_base = { size =	2	current_size = 	2	} 
} #Corinth
#province = { id =	326	naval_base = { size =	2	current_size = 	2	} } #Varna
province = { id =	365 naval_base = { size =	4	current_size = 	4	} } ## Thessaloniki - Thrace - Balkan
province = { 
	id =	1056	
	naval_base = { size =	7	current_size = 	7	}
	air_base = { size =	7	current_size = 	7	} 
} #Gaziantep

province =
{ id       = 409
  anti_air = 5
  ic = 6
  landfort = 3
  coastalfort = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}  #constantinople/istanbul

province = { id = 1172 anti_air = 1 } # Jerusalem

province =
{ id         = 1008
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Tel Aviv
province =
{ id       = 379
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}            # Rodos
province =
{ id         = 1076
  anti_air   = 2 #4
  #air_base   = { size = 6 current_size = 6 }
  #naval_base = { size = 10 current_size = 10 }
}              # Izmit
province =
{ id       = 1075
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
}            # Ankara
province =
{ id          = 429
  anti_air    = 1
  air_base    = { size = 3 current_size = 3 }
  naval_base  = { size = 3 current_size = 3 }
  coastalfort = 1
  oilpool     = 100
  supplypool  = 500
}               # Malta
province =
{ id       = 388
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}            # Cyprus
province =
{ id         = 1019
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Beirut

province = {
	id =	343
	naval_base = { size =	4	current_size = 	4	}
	air_base = { size =	4	current_size = 	4	}
} # Dubrovnik - Croatia - Balkan
province = {
	id =	359
	naval_base = { size =	4	current_size = 	4	}
	air_base = { size =	4	current_size = 	4	}
} # Tirana - Albania - Balkan
province = {
	id =	382
	naval_base = { size =	4	current_size = 	4	}
	air_base = { size =	4	current_size = 	4	}
} # Irakleio - Greek Island - Balkan
province = {
	id =	377
	naval_base = { size =	10	current_size = 	10	}
	air_base = { size =	10	current_size = 	10	}
} # Athens - Attica - Balkan
province = { id =	355	air_base = { size =	8	current_size = 	8	} } #sarajevo
province = { 
	id =	1021	
	naval_base = { size =	1	current_size = 	1	}
	air_base = { size =	1	current_size = 	1	}
} #Aleppo
province = { 
	id =	1078	
	naval_base = { size =	2	current_size = 	2	}
	air_base = { size =	2	current_size = 	2	} 
} #Bursa

### France
province = { id = 114   # Bruges - Flanders - Benelux
   naval_base = { size = 3 current_size = 3 }
   anti_air = 1
 }
province = { id = 125   # Rotterdam - Netherlands - Benelux
   anti_air = 2
   naval_base = { size = 8 current_size = 8 }
 }
province = { id = 122   # Amsterdam - Netherlands - Benelux
   anti_air = 2
   naval_base = { size = 8 current_size = 8 }
   air_base = { size = 8 current_size = 8 }
 }

### Scandinavia
province = { id = 483   # Oslo - Southern Norway - Norway
   anti_air = 2
   air_base = { size = 4 current_size = 4 }
   naval_base = { size = 4 current_size = 4 }
   coastalfort = 3
 }
province = { id = 493   # Trondheim - Central Norway - Norway
   coastalfort = 2
 }
province = { id = 495   # Narvik - Central Norway - Norway
   anti_air = 1
   naval_base = { size = 3 current_size = 3 }
   air_base = { size = 1 current_size = 1 }
 }
province = {
	id = 294
	air_base   = { size = 8 current_size = 8 }
	Naval_base = { size = 8 current_size = 8 }
} #Copenhagen

#province = { 
#	id =	220	
#	naval_base = { size =	2	current_size = 	2	} 
#	air_base = { size =	2	current_size = 	2	} 
#} #Arhus

### Lithuania
province = { id = 270   # Tallinn - Estonia - Baltic States
   anti_air = 2
   naval_base = { size = 6 current_size = 6 }
   air_base = { size = 4 current_size = 4 }
 }
province = { id = 264   # Riga - Latvia - Baltic States
   anti_air = 1
   air_base = { size = 1 current_size = 1 }
   naval_base = { size = 3 current_size = 3 }
 }
 
### United Arab

province = {
	id =	1032
	naval_base = { size =	3	current_size = 	3	}
	air_base = { size =	3	current_size = 	3	}
} # Basrah - Iraq - Middle East

province =
{ id         = 1048
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
} #medina
#province = { 
#	id =	1041	
#	naval_base = { size =	3	current_size = 	3	}
#	air_base = { size =	3	current_size = 	3	} 
#} #Kuwait


### Korea

province = {
	id =	1228
	naval_base = { size =	6	current_size = 	6	}
	air_base = { size =	6	current_size = 	6	}
} # Seoul - Seoul - Korea

province = { id = 1232   # Busan - Seoul - Korea
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
}
province = { id = 1226   # Ganggye - Pyongyang - Korea
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
} 

### Persia

province = {
	id =	1089
	anti_air = 1
	naval_base = { size =	6	current_size = 	6	}
	air_base = { size =	6	current_size = 	6	}
} #Ahvaz

province =
{ id       = 1091
  anti_air = 3
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 5 current_size = 5 }
} #Gameroon

###

province =
{ id       = 1099
  anti_air = 3
  air_base = { size = 5 current_size = 5 }
} #samarkand


province =
{ id       = 94
  supplypool = 100
} #Corsica
