###############################
# Victory points distribution #
###############################

#province = { id = 113 points = 1 } # Falun
#province = { id = 540 points = 1 } # San José
#province = { id = 755 points = 1 } # Villahermosa
#province = { id = 893 points = 1 } # Santiago
#province = { id = 1095 points = 1 } # Banana
#province = { id = 1096 points = 1 } # Loanda
#province = { id = 1100 points = 5 } # Nova Lisboa
#province = { id = 1178 points = 1 } # Asahikawa
#province = { id = 1182 points = 5 } # Fukushima
#province = { id = 1232 points = 1 } # Hankou
#province = { id = 1234 points = 1 } # Wuhu
#province = { id = 1253 points = 1 } # Wuchang
#province = { id = 1268 points = 1 } # Nancheng
#province = { id = 1282 points = 1 } # Kangding
#province = { id = 1348 points = 1 } # Singora
#province = { id = 1373 points = 1 } # Spassk-Dalnij
#province = { id = 1420 points = 1 } # Khobdo
#province = { id = 1498 points = 1 } # Babolsar
#province = { id = 1525 points = 1 } # Okhotsk
#province = { id = 1535 points = 3 } # Angutikha
#province = { id = 1738 points = 1 } # Bataan
#province = { id = 168 points = 2 } #gorkij
#province = { id = 652 points = 1 } #andros
#province = { id = 381 points = 2 } #Rijeka


###############################################
# Germany
###############################################

province = { id = 138 points = 25 } # Frankfurt 5
province = { id = 163 points = 4 } #Berlin 30
province = { id = 154 points = 5   } #Hamburg
province = { id = 152 points = 5   } #Kiel
#province = { id = 171 points = 5   } #Erfurt
province = { id = 145 points = 10  } #Essen 25
#province = { id = 177 points = 5  } #Nürnberg/Nurnberg
province = { id = 146 points = 5   } #Hannover
province = { id = 173 points = 3  } #Dresden 5
province = { id = 131 points = 10  } #Köln/Koln/Cologne
province = { id = 170 points = 3  } #Leipzig 5
province = { id = 134 points = 5  } #Stuttgart
province = { id = 179 points = 10 } #München/Munich
province = { id = 184 points = 2 } # Koenigsberg

province = {	id = 429	points = 3 }#Malta 1
province = {	id = 1432	points = 5 }#Singapore
province = { id = 1371 points = 2	} #Hongkong

###############################################
# Great Britain
###############################################

province = {	id = 29		points = 20	}#London 30
#province = {	id = 15		points = 10	}#Newcastle
province = {	id = 24		points = 5	}#Birgmingham 10
province = {	id = 12		points = 2	}#Edinburgh 15
#province = {	id = 19  	points = 5	}#Bistrol
province = {	id = 22 	points = 1	}#Cardiff 5
#province = {	id = 17  	points = 5	}#Liverpool
province = {	id = 11		points = 5	}#Glasgow
province = { id = 13 points = 2 } # Sunderland

province = { id = 1362 points = 1 } #Taipei

###############################################
# France
###############################################
province = {	id = 55		points = 25	}#Paris
#province = {	id = 74	    points = 5	}#Vichy
province = {	id = 107	points = 2	}#Strassbourg
province = {	id = 105	points = 2	}#Colmar 7
province = {	id = 44		points = 5	}#Caen
#province = {	id = 50		points = 5	}#Amiens
#province = {	id = 66		points = 5	}#Orleans
province = {	id = 37	    points = 1	}#Brest 10
#province = {	id = 39	    points = 10	}#Lorient
#province = {	id = 100	points = 10	}#Verdun
province = {	id = 85 	points = 2	}#Lyon 10
province = { id = 58 points = 2 } # Le Mans #1
province = { id = 63 points = 2 } # Auxerre
province = { id = 52 points = 2 } # Lille
province = { id = 37 points = 2 } #brest #1
province = { id = 38 points = 1 } #rennes

#Luxemburg
province = { id = 109 points = 1 }#Luxemburg

#Belgium
province = { id = 116 points = 3 }#Bruxelles
#province = { id = 115 points = 2 }#Antwerpen
#province = { id = 108 points = 1 }#Liege

#Occitania
province = {	id = 89 	points = 2	}#Marseilles 10
province = {	id = 68 	points = 5	}#Bordeaux 15
province = {	id = 77 	points = 2	}#Toulouse 10


###############################################
# Italy
###############################################
province = {	id = 419	points = 15	}#Roma
province = {	id = 407	points = 7	}#Milano
province = {	id = 400	points = 7	}#Venezia
province = {	id = 396	points = 7	}#Genoa
province = {	id = 421	points = 6 }#Napoli
province = {	id = 430	points = 5 }#Palermo
province = {	id = 411	points = 5 }#Bologna
province = {	id = 422	points = 5 }#Tarento
province = {	id = 750	points = 3 }#Tripoli

###############################################
# Georgia
###############################################

province = { id = 706 points = 2 } # Astrakhan 1
province = { id = 709 points = 2 } # Tblisi
province = { id = 693 points = 1 } #Maykop 2

###############################################
# Russia
###############################################
province = {	id = 572	points = 20	}#Moscow 10
province = {	id = 663	points = 5	}#Stalingrad 10
province = {	id = 1191	points = 10	}#Vladivostok
province = {	id = 542	points = 5	}#Archangelsk
province = {	id = 590	points = 2	}#Vitebsk
province = {	id = 569	points = 2	}#Kalinin
#province = {	id = 579	points = 2	}#Kaluga
#province = {	id = 1162	points = 3	}#Irkutsk
#province = {	id = 1151	points = 3	}#Sverdlovsk
province = {	id = 668	points = 2	}#Kujbysjev 1
province = {	id = 1103	points = 3	}#Tashkent 1
province = {	id = 504	points = 1	}#Alma-Ata
province = {	id = 1138	points = 1	}#Omsk
province = {	id = 1142	points = 1	}#Novosibirsk
#province = {	id = 1186	points = 1	}#Okhotsk
province = {	id = 1179	points = 1	}#Yakutsk

province = { id = 1132 points = 2 } #Chelyabinsk
province = { id = 669 points = 2 } #saratov
province = { id = 576 points = 2 } # Kaluga
province = { id = 1195 points = 3 } # Tetyukhe

###############################################
# USA/American Federation
###############################################

province = {	id = 1809	points = 1	}#Washington 10
province = {	id = 1908	points = 1	}#Denver 10
province = {	id = 1858	points = 1	}#Rapid City
province = {	id = 1860	points = 1	}#Omaha
province = {	id = 1914	points = 1	}#Kansas City
province = {	id = 1912	points = 1	}#Tulsa
province = {	id = 1918	points = 1	}#Little Rock
province = {	id = 1836	points = 1	}#Springfield, MI
province = {	id = 1833	points = 1	}#St.Louis 5
province = {	id = 1838	points = 1	}#Des Moines
province = {	id = 1839	points = 1	}#Milwaukee
province = {	id = 1832	points = 1	}#Chicago 10
province = {	id = 1828	points = 1	}#Indianapolis
province = {	id = 1845	points = 1	}#Detroit 5
province = {	id = 1825	points = 1	}#Cleveland
province = {	id = 1819	points = 1	}#Louisville
province = {	id = 1934	points = 1	}#Nashville
province = {	id = 1925	points = 1	}#Jackson
province = {	id = 1944	points = 1	}#Mobile
province = {	id = 1953	points = 1	}#Miami
province = {	id = 1955	points = 1	}#Atlanta 10
#province = {	id = 1957	points = 1	}#Columbia
#province = {	id = 1962	points = 1	}#Charlotte
province = {	id = 1960	points = 1	}#Charleston
province = {	id = 1812	points = 1	}#Norfolk
province = {	id = 1805	points = 1	}#Philadelphia 5
province = {	id = 1806	points = 1	}#Pittsburgh
province = {	id = 1795	points = 10	}#New York
province = {	id = 1791	points = 1	}#Buffalo
province = {	id = 1789	points = 10	}#Boston 5
province = {	id = 1787	points = 1	}#Concord
#province = {	id = 1907	points = 1	}#Cheyenne
province = {	id = 1931	points = 1	}#New Orleans 5
province = {	id = 2111	points = 1	}#Toronto 10

province = { id = 1963 points = 1 } # Wilmington
province = { id = 1954 points = 1 } # Macon

###############################################
# Canada/Vinland
###############################################

province = {	id = 2119	points = 1	}#Montreal 5
province = {	id = 2108	points = 1	}#Ottawa 20
province = {	id = 2106	points = 1	}#Winnipeg 5
province = {	id = 2089	points = 1	}#Vancouver 10
#province = {	id = 2117	points = 5	}#Quebec
province = {	id = 2132	points = 1	}#Halifax 15
province = {	id = 1856	points = 1	}#Bismarck
province = {	id = 1847	points = 1	}#Minneapolis


###############################################
# Americas
###############################################

#Brazil/Muhajedz
province = { id = 2075 points = 2 }#Rio de Janeiro 3
province = { id = 2071 points = 2 }#Recife
province = { id = 2073 points = 2 }#Salvador
province = { id = 2068 points = 2 }#Belém
province = { id = 2074 points = 2 }#Vitória
province = { id = 2059 points = 2 }#São Paulo
#province = { id = 2057 points = 2 }#Curitiba
province = { id = 2067 points = 2 }#Goiás

#Venezuela/Gustavia
province = { id = 1993 points = 2 }#Caracas
province = { id = 1988 points = 2 }#Maracaibo

#Cuba/Tarrbitz
province = { id = 1776 points = 2 }#La Habana
province = { id = 1762 points = 1 } #curacao
province = { id = 1782 points = 1 } #Jamaica
#province = { id = 1778 points = 1 } # Guantánamo

#Haiti/Dominican/Mansur
province = { id = 1781 points = 4 }#Port-au-Prince 1

#Fabur
province = { id = 1765 points = 2 } #Puerto Rico
province = { id = 1758 points = 1 } #Trinidad

#Nova Aquitania
province = { id = 2000 points = 2 } # Cayenne

###############################################
# Mazula
###############################################

#Mexico
#province = { id = 1977 points = 2 }#Ciudad de Juarez
#province = { id = 1968 points = 1 }#Veracruz
#province = { id = 1980 points = 1 }#Culican
province = { id = 1975 points = 1 }#Monterrey
province = { id = 1972 points = 1 }#Acapulco
province = { id = 1974 points = 20 } # Mexico City
province = { id = 1969 points = 1 } # Puebla
province = {	id = 1734	points = 1	}#Honolulu
province = {	id = 1924	points = 2	}#Dallas 1
province = {	id = 1926	points = 1	}#San Antonio
province = {	id = 1928	points = 3	}#Houston 1
province = {	id = 1889	points = 3	}#San Francisco 5
province = {	id = 1888	points = 3	}#Sacramento 10
province = {	id = 1887	points = 3	}#Los Angeles 1
province = {	id = 1886	points = 1	}#San Diego
province = {	id = 1900	points = 1	}#Phoenix
province = { id = 2142 points = 1 } # Anchorage
province = {	id = 1904	points = 1	}#Albuquerque
province = {	id = 1874	points = 1	}#Seattle
province = {	id = 1878	points = 1	}#Portland
province = {	id = 1872	points = 1	}#Spokane
province = {	id = 1896	points = 1	}#Salt Lake City
province = {	id = 1864	points = 1	}#Great Falls

province = { id = 1871 points = 1 } # Boise

###############################################
# Qtizi
###############################################

#province = { id = 1982 points = 1 }
province = { id = 1986 points = 2 } # Barranquilla

#Panama
province = { id = 2078 points = 1 }#Panama
province = { id = 889 points = 2 }#Colon (Channel Zone) 5

#Costa Rica
#province = { id = 2081 points = 1 }#San José

#Nicaragua
province = { id = 2080 points = 1 }#Managua

#Honduras
province = { id = 2085 points = 1 }#Tegucigalpa

#El Salvador
province = { id = 2079 points = 1 }#San Salvado

#Guatemala
province = { id = 2088 points = 1 }#Guatemala

#Santo Domingo
#province = { id = 1780 points = 1 }#Santo Domingo

###############################################
# Jadakal
###############################################

#Chile/Asmunakal/Jadakal
province = { id = 2023 points = 4 }#Santiago
province = { id = 2025 points = 2 }#Antofagasta
province = { id = 2030 points = 1 } # Punta Arenas

#Argentine/Jidligrib
province = { id = 2050 points = 6 }#Buenos Aires
province = { id = 2053 points = 2 }#Mar del Plata
province = { id = 2049 points = 2 }#Corrientes
province = { id = 2054 points = 2 }#Córdoba
province = { id = 2027 points = 1 }#San Miguel de Tucumán

#Uruguay
province = { id = 2052 points = 1 }#Montevideo

#Bolivia
province = { id = 2020 points = 2 }#La Paz

#Paraguay
province = { id = 2047 points = 1 }#Asunción

###############################################
# Tarwajal
###############################################

#Colombia
province = { id = 1991 points = 2 }#Bogotá
province = { id = 1990 points = 2 }#Cascuta
#province = { id = 1985 points = 2 }#Cali

#Ecuador
#province = { id = 2042 points = 2 }#Quito
province = { id = 2040 points = 5 } # Santiago 10

#Peru
province = { id = 2016 points = 2 }#Lima
province = { id = 2017 points = 2 }#Arequipa

###############################################
# Austria
###############################################

province = {	id = 195	points = 10 }#Vienna 6
province = {	id = 192	points = 1 }#Salzburg 2
province = {	id = 189	points = 2 }#Innsbruck
province = {	id = 190	points = 2 }#Graz

#Silesia
province = {	id = 167	points = 2 }#Breslau

#Hungary
province = {	id = 284	points = 4 }#Budapest 2
province = {	id = 277	points = 2 }#Pecs
province = {	id = 281	points = 1 }#Debrecen
province = { 	id = 208	points = 2 }#Bratislava 4
province = { 	id = 209	points = 2 }#Kosice
province = {	id = 288	points = 2 }#Cluj-Napoca

#Czech Rep/Bohemia
province = { 	id = 207	points = 5 }#Prague #6
#province = {    id = 199    points = 1 }#Plzen
province = { id = 196 points = 1 } # Brno

###############################################
# Central Europe
###############################################

#Schweiz/Switzerland
province = {	id = 392	points = 1 }#Bern
province = {	id = 389	points = 1 }#Zürich

#Romania/Roumania
province = {	id = 316	points = 4 }#Bucharest
province = {	id = 311	points = 2 }#Ploesti
province = {	id = 293	points = 2 }#Miercurea Ciuc

###############################################
# Lithuania
###############################################

province = {	id = 644	points = 2	}#Rostov
province = {	id = 641	points = 2	}#Sevastopol
province = {	id = 626	points = 2	}#Odessa
province = {	id = 636	points = 2	}#Kharkov
province = {	id = 617	points = 5	}#Kiev
province = {	id = 599	points = 5	}# Minsk
province = {	id = 589	points = 2	}#Smolensk 5

#Estonia
province = { id = 270 points = 2 }#Tallinn

#Latvia
province = { id = 264 points = 2 }#Riga

#Lithuania
#province = { id = 258 points = 2 }#Vilnius
province = { id = 262 points = 2 } # Kaunas

#Poland
province = {	id = 232	points = 4 }#Warsaw
province = {	id = 181	points = 2 }#Danzig
province = {	id = 223	points = 2 }#Lodz
province = {	id = 235	points = 2 }#Krakow
province = {	id = 242	points = 2 }#Lvov
province = {	id = 255	points = 2 }#Grodno

###############################################
# Union of Rome
###############################################

province = {	id = 713	points = 2	} #Baku 10
province = {	id = 711	points = 2	}#Yerevan

#Bulgaria
province = {	id = 321	points = 5 }#Sofia 1
province = {	id = 324	points = 1 }#Plovdiv
province = {	id = 326	points = 1 }#Varna

#Greece
province = {	id = 377	points = 5 }#Athinai 1
province = {	id = 382	points = 1 }#Crete/Irakleio
province = {	id = 365	points = 1 }#Thessaloniki

#Albania
province = {	id = 359	points = 2 }#Tirane

#Yugoslavia
province = {	id = 338	points = 2 }#Belgrade 4
province = {	id = 352	points = 1 }#Zagreb
province = {	id = 349	points = 1 }#Ljubljana
province = {	id = 333	points = 1 }#Skopje
province = {	id = 355	points = 1 }#Sarajevo
province = { id = 350 points = 1 } # Split

################################
# Scandinavia
################################

#Sweden
province = { id = 2159 points = 5 }#Stockholm 4
province = { id = 2153 points = 2 }#Göteborg
province = { id = 2152 points = 1 }#Malmö
province = { id = 2161 points = 1 }#Karlstadt
#province = { id = 2164 points = 1 }#Umea

#Denmark#
province = { id = 294 points = 1 }#Kopenhavn
province = { id = 220 points = 1 }#Aarhus
province = { id = 219 points = 1 }#Odense

#Norway#
province = { id = 483 points = 1 }#Oslo 5
province = { id = 495 points = 2 }#Narvik 5
province = { id = 493 points = 2 }#Trondheim 5

#Finland
province = { id = 525 points = 3 }#Helsinki
province = { id = 531 points = 1 }#Vipuri
province = { id = 524 points = 1 }#Turku
province = { id = 521 points = 1 }#Vaasa
province = { id = 517 points = 1 }#Petsamo
province = { id = 553 points = 2 }#Leningrad/Odinholm 10
province = {	id = 535	points = 2	}#Murmansk 5


###############################################
# Western Europe
###############################################

#Netherlands
province = { id = 122 points = 5 }#Amsterdam
#province = { id = 119 points = 1 }#Arnhem 5
province = { id = 118 points = 1 }#Eindhoven 5

#Spain/Iberia
province = { id = 460 points = 1 }#Madrid 3
#province = { id = 473 points = 0 }#Cadiz
province = { id = 464 points = 2 }#Valencia
province = { id = 440 points = 2 }#Barcelona
province = { id = 471 points = 1 }#Malaga
province = { id = 441 points = 1 }#Coruna
province = { id = 451 points = 1 }#Burgos
#province = { id = 474 points = 1 }#Sevilla
#province = { id = 442 points = 1 }#Zaragoza
province = { id = 457 points = 3 } # Toledo
province = { id = 455 points = 2 } # Guadalajara
province = { id = 472 points = 2 } # Huelva
province = { id = 467 points = 30 } # Cordoba
province = { id = 348 points = 7 } # Gibraltar
province = { id = 463 points = 1 } # Murcia
province = { id = 436 points = 1 } # Tarragona
province = { id = 443 points = 2 } # Bilbao

#Portugal
province = { id = 476 points = 5 }#Lissabon 3
province = { id = 481 points = 1 }#Porto
province = { id = 2261 points = 1 }#Cap Verde

#Ireland
province = { id = 34 points = 3 } # Dublin 2
province = { id = 36 points = 1 } # Belfast #2
province = { id = 31 points = 1 } # Cork #2

###############################################
# Middle East
###############################################

#Turkey
province = {	id = 409	points = 30 }#Istanbul 3
province = {	id = 1076	points = 1 }#Izmir
province = {	id = 1077	points = 1 }#Izmit
province = {	id = 1075	points = 15 }#Ankara 2
province = {	id = 1067	points = 1 }#Trebizon
province = {	id = 1056	points = 1 }#Gaziantep
province = {	id = 1063	points = 1 }#Erzurum

#Persia
province = {	id = 1085	points = 2 }#Teheran
province = {	id = 1089	points = 1 }#Ahvaz
#province = {	id = 1088	points = 1 }#Shiraz
province = {	id = 1086	points = 1 }#Esfahan
#province = {	id = 1091	points = 1 }#Gameroon
province = {	id = 1083	points = 1 }#Tabriz

###############################################
# Arabia
###############################################

province = {	id = 1052	points = 2 }#Muscat
#province = {	id = 1045	points = 1 }#Riyadh
province = { id = 1049 points = 1 } #mecca
province = {	id = 1034	points = 3 }#Bagdad
province = {	id = 1029	points = 2 }#Mosul
province = {	id = 1032	points = 1 }#Basra
province = {	id = 1016	points = 5	}#Damascus

#Palestine
province = { id = 1172 points = 1 } # Jerusalem

###############################################
# Africa
###############################################

#Egypt
province = {	id = 900	points = 5	}#Suez
province = { id = 791 points = 5 } # Port Said
province = { id = 787 points = 2 } # Cairo
province = { id = 789 points = 5 } # Alexandria
province = { id = 810 points = 1 } # Khartoum
province = { id = 765 points = 3 } # Tobruk
province = { id = 761 points = 1 } # Bengazi

#Ethiopia/Adal
province = { id = 825 points = 2 }#Addis Abeba
#province = { id = 827 points = 1 }#Gode
province = { id = 836 points = 1 }#Mogadishu

#Liberia/Friland
#province = { id = 969 points = 1 }#Monrovia
province = { id = 950 points = 1 } # Lome

#South africa/Ljansitar
province = { id = 880 points = 3 }#Capetown
province = { id = 876 points = 3 }#Johannesburg
province = { id = 881 points = 2 }#Port Elizabeth
province = { id = 872 points = 2 }#Durban
province = { id = 855 points = 1 }#Lourenco Marques

#Congo
province = { id = 850 points = 1 }#Daresalam 10
#province = { id = 841 points = 2  }#Nairobi
#province = { id = 929 points = 2  }#Lagos
#province = { id = 911 points = 2  }#Douala
province = { id = 915 points = 2 } # Libreville
province = { id = 898 points = 1 }#Leopoldville
province = { id = 899 points = 1 }#Elisabethville

#Morocco
province = {	id = 718	points = 2 } #Casablanca 5
province = { id = 995 points = 1 } #Azores

#Portugal/Congo/Angola
#province = { id = 895 points = 1 }#Luanda
province = { id = 892 points = 1 }#Lobito

###############################################
# African Union
###############################################
province = {	id = 727	points = 5	}#Algiers 10
province = {	id = 747	points = 10	}#Tunis 5
province = {	id = 978	points = 5	}#Dakar 10
#province = {	id = 728	points = 1	}#Oran
#province = {	id = 962	points = 5	}#Abidjan
#province = {	id = 957	points = 1	}#Ougadadougou
#province = {	id = 732	points = 2	}#Djeffa
#province = {	id = 735	points = 2	}#Bone
province = {	id = 742	points = 2	}#Medenine
#province = {	id = 966	points = 1	}#Conakry

###############################################
# Asia
###############################################

#Bhutan
province = { id = 1456 points = 1 } # Punakha
province = { id = 1457 points = 1 } # Nepal: had no VP

#Korea
province = { id = 1232 points = 1 } # Busan
province = { id = 1228 points = 1 } # Seoul
province = { id = 1221 points = 1 } # Pyongyang
#province = { id = 1222 points = 1 }

###############################################
# India
###############################################

province = { id = 1517 points = 5 } # Bombay
province = { id = 1447 points = 5 } # Calcutta
province = { id = 1459 points = 5 } # Delhi
province = { id = 1500 points = 1 } #madras
province = { id = 1518 points = 1 } #ahmedabad
province = { id = 1497 points = 2 } # Cochin
province = {	id = 1485	points = 1	}#Nagpur
province = {	id = 1504	points = 1	}#Madurai
province = {	id = 1487	points = 1	}#Hyderabad
province = {	id = 1442	points = 1	}#Imphal
province = {	id = 1533	points = 3	}#Karachi

###############################################
# Far East
###############################################

#Cambodia
province = { id = 1427 points = 1 } # Khon Kaen

#Afghanistan
province = { id = 2171 points = 1 } #Kabul
province = { id = 2172 points = 1 } #Herat

#Philippines/Tagalog
province = { id = 1565 points = 3 } #Manila
province = { id = 1569 points = 1 } #Olongapo
#province = { id = 1567 points = 1 } #Baguio
province = { id = 1571 points = 1 } #Mindoro
province = { id = 1573 points = 1 } #Leyte
province = { id = 1578 points = 1 } #Cagayan
province = { id = 1579 points = 1 } #Davao

#Australia/Australasia
province = { id = 1707 points = 2 } #Canberra
province = { id = 1705 points = 3 } #Sydney
province = { id = 1704 points = 2 } #Brisbane
province = { id = 1690 points = 1 } #Perth
province = { id = 1708 points = 2 } #Melbourne
province = { id = 1697 points = 2 } #Darwin
province = { id = 1712 points = 1 } #Adelaide
province = { id = 1703 points = 1 } #Newcastle
province = { id = 1699 points = 1 } #Townsville

#New Zealand
province = { id = 1721 points = 1 } #Wellington
province = { id = 1720 points = 1 } #Auckland
province = { id = 1722 points = 1 } #Christchurch


#The Pacific
#province = { id = 1661 points = 1 } #Iwo Jima
#province = { id = 1683 points = 2 } #Guam
#province = { id = 1680 points = 2 } #Tarawa
#province = { id = 1685 points = 2 } #Saipan
#province = { id = 1670 points = 1 } #Palau
#province = { id = 1669 points = 1 } #Yap
#province = { id = 1667 points = 2 } #Truk
#province = { id = 1590 points = 2 } #Guadalcanal
#province = { id = 1586 points = 1 } #Noumea
#province = { id = 1728 points = 1 } #Fiji
#province = { id = 1749 points = 1 } #Samoa
#province = { id = 1682 points = 1 } #Nauru
##province = { id = 1676 points = 1 } #Kwajalein
#province = { id = 1675 points = 1 } #Eniwetok
##province = { id = 1673 points = 1 } #Wake Island
##province = { id = 1739 points = 1 } #Midway Island
##province = { id = 2150 points = 1 } #Unalaska Island

###############################################
# Ostasien
###############################################

#malaysia
province = {	id = 1433	points = 2  } #Kota Baharu
province = {	id = 1438	points = 1  } #Kualu Lumpur

#indonesia
province = { id = 1636 points = 2 }#Palembang
province = { id = 1647 points = 3 }#Batavia
province = { id = 1641 points = 2 }#Oosthaven
province = { id = 1642 points = 2 }#Medan
#province = { id = 1632 points = 2 }#Balikpapan
province = { id = 1596 points = 2 }#Hollandia
province = { id = 1657 points = 2 } # Makassar

#new guinea
province = { id = 1607 points = 2 } #Port Moresby
province = { id = 1602 points = 1 } #Lae
#province = { id = 1726 points = 1 } #Rabaul
#province = { id = 1587 points = 1 } #Bougainville

#Burma
province = { id = 1415 points = 2 } # Rangoon
province = { id = 1410 points = 1 } # Mandalay
province = { id = 1409 points = 1 } # Lashio

#Siam
province = { id = 1423 points = 3 } #Bangkok
province = { id = 1426 points = 1 } #Phitsanulok
#province = { id = 1431 points = 1 } #Songhla

###############################################
# China
###############################################
province = {	id = 1337	points = 10	}#Nanjing 3
province = {	id = 1338	points = 2	}#Shanghai
province = {	id = 1247	points = 5	}#Beijing
province = {	id = 1241	points = 1	}#Tianjin
province = {	id = 1239	points = 1	}#Jining
province = {	id = 1243	points = 1	}#Baoding
province = {	id = 1340	points = 1	}#Hefei
province = {	id = 1322	points = 1	}#Luoyang
province = {	id = 1325	points = 1	}#Nanyang
#province = {	id = 1318	points = 1	}#Huangshi
#province = {	id = 1344	points = 1	}#Anquing
province = {	id = 1345	points = 1	}#Hangzhou
#province = {	id = 1317	points = 1	}#Wuchan
#province = {	id = 1307	points = 1	}#Huaihua
#province = {	id = 1254	points = 1	}#Hequ
province = {	id = 1299	points = 3	}#Chongqing
province = {	id = 1263	points = 1	}#Tianshui
#province = {	id = 1384	points = 1	}#Luxi
#province = {	id = 1293	points = 1	}#Panzhihua
#province = {	id = 1297	points = 1	}#Chengdu
province = { id = 1328 points = 1 } # Qingdao
province = { id = 1252 points = 2 } #Taiyuan
#province = { id = 1321 points = 1 } # Hainan
province = { id = 1281 points = 1 } # Urumqi
province = { id = 1284 points = 1 } # Xining

province = { id = 1310 points = 2 } # Changde

#Nationalists
province = {	id = 1389	points = 1	}#Baoshan
province = {	id = 1354	points = 1	}#Ganzhou
province = {	id = 1312	points = 1	}#Hengyang
province = {	id = 1305	points = 1	}#Guiyang
province = {	id = 1303	points = 1	}#Anshun
province = {	id = 1390	points = 3	}#Kunming
province = {	id = 1292	points = 1	}#Ya'an
province = { id = 1381 points = 1 } # Bose
province = { id = 1369 points = 5 } # Guangzhou
province = { id = 1380 points = 1 } # Liuzhou
province = { id = 1378 points = 1 } # Guilin
province = { id = 1372 points = 1 }#Macao

#Communists
province = { id = 1260 points = 1 } # Yuling
province = { id = 1259 points = 1 } # Yan'an

#Shanxi (CSX)
province = { id = 1270 points = 1 } #Linhe
province = { id = 1330 points = 1 }

#Xibei San Ma
#province = { id = 1277 points = 1 }

#Tibet
province = {	id = 1289	points = 2 }#Lhasa

#Mongolia
province = {	id = 1124	points = 1 }#Urga

#Manchuko
province = {	id = 1236	points = 1 }#Chengde 2
province = {	id = 1199	points = 4 }#Harbin
province = {	id = 1208	points = 1 }#Changchun 2

#Annam/Vietnam
province = {	id = 1399	points = 5 }#Saigon
province = {	id = 1395	points = 5 }#Hanoi
#province = { id = 1405 points = 1 }

###############################################
# Japan
###############################################

province = {	id = 1552	points = 10	}#Tokyo
province = {	id = 1557	points = 10	}#Nagoya
province = {	id = 1553	points = 10	}#Osaka
province = {	id = 1554	points = 10	}#Hiroshima
province = {	id = 1545	points = 2	}#Sapporo
province = {	id = 1547	points = 5	}#Akita
province = {	id = 1549	points = 5	}#Sendai
province = {	id = 1550	points = 5	}#Yokohama
province = {	id = 1551	points = 5	}#Niigata
province = {	id = 1556	points = 5	}#Kanazawa
province = {	id = 1559	points = 5	}#Matsuyama
province = {	id = 1558	points = 5	}#Kagashima
province = {	id = 1663	points = 1	}#Motoyama
province = {	id = 1542	points = 1	}#Toyohare
province = {	id = 1563	points = 5	}#Southern Okinawa
province = {	id = 1564	points = 5	}#Northern Okinawa
