#####################
# Country main data #
#####################

country =
{ tag                    = MEX
  ai = "mazula.ai"
  dissent		 = 5
#Great Power
  energy                 = 5000
  metal                  = 2500
  rare_materials         = 1000
  oil                    = 500
  supplies               = 500
  money                  = 100
  manpower               = 242
  transports             = 200
  escorts                = 20
  capital                = 1974
  research_mod = 0.75
  peacetime_ic_mod = 0.6
  SpyInfo                = { country = "MEX" NumberOfSpies = 4 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8 #9
    political_left    = 5
    freedom           = 7 #10
    free_market       = 7 #9
    professional_army = 4
    defense_lobby     = 6 #5
    interventionism   = 5 #3
  }
	diplomacy =
  { relation = { tag = UAU value = 80 guaranteed = { day = 11 month = june year = 1933 } }
    relation = { tag = PAN value = 150 }
    relation = { tag = SPA value = 100 }
    relation = { tag = SAF value = 200 access = yes }
    relation = { tag = GER value = 50 }
    relation = { tag = SPA value = 100 }
    relation = { tag = HAI value = -100 guaranteed = { day = 11 month = june year = 1933 } }
    relation = { tag = JAP value = 50 }
    relation = { tag = CUB value = 75 guaranteed = { day = 11 month = june year = 1933 } }
    relation = { tag = DOM value = 25 guaranteed = { day = 11 month = june year = 1933 } }
  }
	nationalprovinces      = {
		1966 1970 1968 1974 1972 1971 1973 1967 1975 1976 1969 1978 1980 1977 1979 1981 1982
		2087 2086 #1965
		#hawaii
		1734 1735 1736 1737
		#texas
		1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
		#california
		1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
		#nevada
		1893 1894 1895
		#arizona
		1900 1901 1902
		#utah
		1896 1897 1898 1899
		#washington
		1872 1873 1874 1875 1876 1877
		#oregon
		1878 1879 1880 1881 1882
		#washington
		1872 1873 1874 1875 1876 1877
		#oregon
		1878 1879 1880 1881 1882
		#new mexico
		1903 1904 1905 1906
		#idaho
		1861 1869 1870 1871
		#montana
		1862 1863 1864 1865 1868
		#alaska
		2139 2140 2141 2142 2143 2144 2145 2146 2147 2148 2149
		#northwest territories
		2099
		#alberta
		2103 2104 2105
		#british columbia
		2089 2090 2091 2092
		#yukon
		2093 2094 2095
		#colorado
		1907 1908 1909
		#kansas
		1910 1914
		#oklahoma
		1911 1912 1913 1916
		#aleutians
		2174 2150 2151
		#nebraska
		1859
		#barasya
		#louisianna
		1930 1932 1934 #1931 1929
		#mississippi
		#1937 1938
		#arkansas
		#1933
		#nebraska
		#1858 1866
		#omaha
		#1860
		#bismarck
		#1856
		#montana
		#1851 1853 1867
	}
	ownedprovinces    = {
		1966 1970 1968 1974 1972 1971 1973 1967 1975 1976 1969 1978 1980 1977 1979 1981 1982
		2087 2086 #1965
		#panama
		#889
		#tierra del fuego
		2043 2044
		#pacific islands
		1740 1743 1746 1749 1750 1745 1747 1751
		1678 1679 1680 1681 1687
		1728 1729 1733 1734 1735 1736 1737 1738 1739
		1677 1673 1731 1732 1741 1742 1748
		1730 1744
		#texas
		1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
		#california
		1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
		#nevada
		1893 1894 1895
		#arizona
		1900 1901 1902
		#utah
		1896 1897 1898 1899
		#washington
		1872 1873 1874 1875 1876 1877
		#oregon
		1878 1879 1880 1881 1882
		#new mexico
		1903 1904 1905 1906
		#idaho
		1861 1869 1870 1871
		#montana
		1862 1863 1864 1865 1868
		#alaska
		2139 2140 2141 2142 2143 2144 2145 2146 2147 2148 2149
		#northwest territories
		2099
		#alberta
		2103 2104 2105
		#british columbia
		2089 2090 2091 2092
		#yukon
		2093 2094 2095
		#aleutians
		2174 2150 2151
		#barasya
		#louisianna
		1930 1932 1934
	}
	controlledprovinces    = {
		1966 1970 1968 1974 1972 1971 1973 1967 1975 1976 1969 1978 1980 1977 1979 1981 1982
		2087 2086 #1965
		#panama
		#889
		#tierra del fuego
		2043 2044
		#pacific islands
		1740 1743 1746 1749 1750 1745 1747 1751
		1678 1679 1680 1681 1687
		1728 1729 1733 1734 1735 1736 1737 1738 1739
		1677 1673 1731 1732 1741 1742 1748
		1730 1744
		#texas
		1919 1920 1921 1922 1923 1924 1925 1926 1927 1928
		#california
		1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
		#nevada
		1893 1894 1895
		#arizona
		1900 1901 1902
		#utah
		1896 1897 1898 1899
		#washington
		1872 1873 1874 1875 1876 1877
		#oregon
		1878 1879 1880 1881 1882
		#new mexico
		1903 1904 1905 1906
		#idaho
		1861 1869 1870 1871
		#montana
		1862 1863 1864 1865 1868
		#alaska
		2139 2140 2141 2142 2143 2144 2145 2146 2147 2148 2149
		#northwest territories
		2099
		#alberta
		2103 2104 2105
		#british columbia
		2089 2090 2091 2092
		#yukon
		2093 2094 2095
		#aleutians
		2174 2150 2151
		#barasya
		#louisianna
		1930 1932 1934
	}
	claimedprovinces	= {
		#panama
		#889
		#tierra del fuego
		2043 2044
		#pacific islands
		1740 1743 1746 1749 1750 1745 1747 1751
		1678 1679 1680 1681 1687
		1728 1729 1733 1738 1739
		1677 1673 1731 1732 1741 1742 1748
		1730 1744
	}

  techapps = {
	##Air Doctrines##
	9010 #Air Superiority
	9020 #Flying Circus
	9030 #Force Substitution
	#9090 #Operational Dest
	#9140 #Strat Dest

	##Aircraft##
	4010 #Interwar Fighter
	4020 #Early Fighter
	#4030 #Basic Interceptor
	#4050 #Basic Escort
	4120 #Interwar Bomber
	4130 #Early Bomber
	#4140 #Basic Tac Bomber
	#4190 #Basic Naval Bomber
	4220 #Basic Strat Bomber
	#4250 #Basic Transport

	##Armor##
	2010 #Great War Tank
	2020 #Tankette
	2150 #Basic Armored Car
	2290 #GW Light Artillery
	2300 #GW Medium Artillery
	2310 #GW Heavy Artillery
	2320 #Early Artillery
	2400 #Early Anti-Tank
	2450 #GW Flak
	#2460 #Early Flak
	2510 #Basic AA Brigade
	
	2030 #Early Tank

	##Industry##
	5010 #Modern Agriculture
	5020 #Mech Agriculture
	5050 #Basic Machine Tools
	5060 #Improved Machine Tools
	#5070 #Advanced Machine Tools
	5080 #Basic Construction
	5090 #Improved Construction
	#5100 #Advanced Construction
	5190 #Basic Oil Refining
	5310 #Census Tabulating
	#5320 #Basic Computer
	
	5470 #Atomic Research Faculty
	5480 #Atomic Research Labs
	5200 #Imp Oil Refining
	7550 #Rocket Testing

	##Infantry##
	1010 #Great War Infantry
	1020 #Early Infantry
	1110 #Early Mountaineers
	1150 #Early Marines
	1190 #Great War Cavalry
	1200 #Early Cavalry
	1210 #Basic Cavalry
	#1220 #Semi Motorized Cavalry
	1310 #Rear Area Supply

	1230 #Basic Motorized Division
	1120 #Basic Mountaineers
	1160 #Basic Marines

	##Land Doctrines - Superior Firepower##
	6010 #Firepower Focus
	6020 #Superior Firepower
	6040 #Delay
	14000 #Great War Hospital

	##Naval Doctrines##
	8010 #Decisive Battle
	8020 #Naval Firepower
	8030 #Fleet Aux Carrier
	8040 #Fleet Aux Sub
	8050 #Convoy Sailing
	8060 #Base Strike

	8090 # Indirect Approach Doctrine
	8100 # Subsidiary Carrier Role Doctrine
	82300 #Basic Amphib Warfare

	##Naval Tech##
	3010 #GW Destroyer
	3020 #Early Destroyer
	3030 #Basic Destroyer
	3040 #Improved Destroyer
	3070 #GW Light Cruiser
	3080 #Early Light Cruiser
	3090 #Basic Light Cruiser
	3100 #Improved Light Cruiser
	3130 #GW Heavy Cruiser
	3140 #Early Heavy Cruiser
	3150 #Basic Heavy Cruiser
	3160 #Improved Heavy Cruiser
	3250 #GW Battleship
	3260 #Early Battleship
	3270 #Basic Battleship
	3280 #Improved Battleship
	3320 #GW Carrier
	3330 #Early Carrier
	3340 #Basic Carrier
	#3350 #Improved Carrier
	3400 #Dive Boat
	3410 #Short Range Sub
	3420 #Med Range Sub
	3430 #Long Range Sub
	
	12100 12110 #CVL
	4900 4910 #CAG
	3810 #Troopship
  }
  headofstate            = { type = 9 id = 36001 }
  headofgovernment       = { type = 9 id = 36002 }
  foreignminister        = { type = 9 id = 36003 }
  armamentminister       = { type = 9 id = 36004 }
  ministerofsecurity     = { type = 9 id = 36005 }
  ministerofintelligence = { type = 9 id = 36006 }
  chiefofstaff           = { type = 9 id = 36007 }
  chiefofarmy            = { type = 9 id = 36008 }
  chiefofnavy            = { type = 9 id = 36009 }
  chiefofair             = { type = 9 id = 36010 }
  #Army
  landunit =
  { id       = { type = 10700 id = 649 }
    location = 1974
    name     = "1st Cavalry Corps"
    division =
    { id     = { type = 10700 id = 650 }
      name   = "Sipahis al-1i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 400 }
      name   = "Sipahis al-6i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10700 id = 651 }
    location = 2104
    name     = "2nd Cavalry Corps"
    division =
    { id     = { type = 10700 id = 652 }
      name   = "Sipahis al-2i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 401 }
      name   = "Sipahis al-7i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10700 id = 653 }
    location = 2089
    name     = "3rd Cavalry Corps"
    division =
    { id     = { type = 10700 id = 654 }
      name   = "Sipahis al-3i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 402 }
      name   = "Sipahis al-8i"
      type   = cavalry
      model  = 2
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10700 id = 655 }
    location = 1889
    name     = "1st Armoured Cavalry Corps"
    division =
    { id     = { type = 10700 id = 656 }
      name   = "1. Armored Division"
      type   = light_armor
      model  = 0
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 403 }
      name   = "1. Motorized Infantry"
      type   = motorized
      model  = 0
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 398 }
      name   = "2. Motorized Infantry"
      type   = motorized
      model  = 0
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10700 id = 657 }
    location = 1896
    name     = "1st Army Corps"
    division =
    { id     = { type = 10700 id = 658 }
      name   = "Central Army Command"
      type   = hq
      model  = 0
    }
    division =
    { id     = { type = 10700 id = 659 }
      name   = "al-Mushati al-1i"
      type   = infantry
	  strength = 50
      model  = 1
      extra  = anti_air
      brigade_model = 0
    }
    division =
    { id     = { type = 10700 id = 660 }
      name   = "al-Mushati al-2i"
      type   = infantry
	  strength = 50
      model  = 1
      extra  = artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 10700 id = 661 }
    location = 1924
    name     = "2nd Army Corps"
    division =
    { id     = { type = 10700 id = 662 }
      name   = "al-Mushati al-3i"
      type   = infantry
	  strength = 50
      model  = 1
      extra  = engineer
      brigade_model = 0
    }
    division =
    { id     = { type = 10700 id = 663 }
      name   = "al-Mushati al-4i"
      type   = infantry
	  strength = 50
      model  = 1
      extra  = artillery
      brigade_model = 0
    }
    division =
    { id     = { type = 10700 id = 664 }
      name   = "al-Mushati al-5i"
      type   = infantry
	  strength = 50
      model  = 1
      extra  = artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 10700 id = 665 }
    location = 1932
    name     = "1st Border Guards"
    division =
    { id     = { type = 10700 id = 666 }
      name   = "al-Mushati al-6i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 399 }
      name   = "al-Mushati al-299i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 404 }
      name   = "al-Mushati al-104i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 667 }
    location = 1930
    name     = "2nd Border Guards"
    division =
    { id     = { type = 10700 id = 668 }
      name   = "al-Mushati al-7i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 405 }
      name   = "al-Mushati al-105i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 406 }
      name   = "al-Mushati al-106i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 669 }
    location = 1920
    name     = "3rd Border Guards"
    division =
    { id     = { type = 10700 id = 670 }
      name   = "al-Mushati al-8i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 407 }
      name   = "al-Mushati al-107i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 408 }
      name   = "al-Mushati al-108i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 671 }
    location = 1921
    name     = "4th Border Guards"
    division =
    { id     = { type = 10700 id = 672 }
      name   = "al-Mushati al-9i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 409 }
      name   = "al-Mushati al-109i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 410 }
      name   = "al-Mushati al-110i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 673 }
    location = 1904
    name     = "5th Border Guards"
    division =
    { id     = { type = 10700 id = 674 }
      name   = "al-Mushati al-10i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 411 }
      name   = "al-Mushati al-111i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 412 }
      name   = "al-Mushati al-112i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 675 }
    location = 1919
    name     = "6th Border Guards"
    division =
    { id     = { type = 10700 id = 676 }
      name   = "al-Mushati al-11i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 413 }
      name   = "al-Mushati al-113i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 414 }
      name   = "al-Mushati al-114i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 677 }
    location = 1868
    name     = "7th Border Guards"
    division =
    { id     = { type = 10700 id = 678 }
      name   = "al-Mushati al-12i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 416 }
      name   = "al-Mushati al-116i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 415 }
      name   = "al-Mushati al-115i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 679 }
    location = 1862
    name     = "8th Border Guards"
    division =
    { id     = { type = 10700 id = 680 }
      name   = "al-Mushati al-13i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 417 }
      name   = "al-Mushati al-117i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 418 }
      name   = "al-Mushati al-118i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 681 }
    location = 1906
    name     = "9th Border Guards"
    division =
    { id     = { type = 10700 id = 682 }
      name   = "al-Mushati al-14i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 419 }
      name   = "al-Mushati al-119i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 420 }
      name   = "al-Mushati al-120i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 683 }
    location = 1869
    name     = "10th Border Guards"
    division =
    { id     = { type = 10700 id = 684 }
      name   = "al-Mushati al-15i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 421 }
      name   = "al-Mushati al-121i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 422 }
      name   = "al-Mushati al-122i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 685 }
    location = 2103
    name     = "11th Border Guards"
    division =
    { id     = { type = 10700 id = 686 }
      name   = "al-Mushati al-16i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 423 }
      name   = "al-Mushati al-123i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 424 }
      name   = "al-Mushati al-124i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 687 }
    location = 1922
    name     = "Republican Marine Corps"
    division =
    { id     = { type = 10700 id = 688 }
      name   = "al-Mushati al-17i"
      type   = marine
      model  = 1
	  strength = 50
      extra  = artillery
      brigade_model = 3
    }
    division =
    { id     = { type = 10700 id = 689 }
      name   = "al-Mushati al-18i"
      type   = marine
      model  = 1
	  strength = 50
    }
    division =
    { id     = { type = 10700 id = 690 }
      name   = "al-Mushati al-19i"
      type   = marine
      model  = 1
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10005 id = 425 }
    location = 2089
    name     = "1. Mountaincorps"
    division =
    { id     = { type = 10005 id = 426 }
      name   = "3. Mountaineers"
      type   = bergsjaeger
      model  = 1
	  strength = 50
    }
    division =
    { id     = { type = 10005 id = 427 }
      name   = "1. Mountaineers"
      type   = bergsjaeger
      model  = 1
	  strength = 50
    }
    division =
    { id     = { type = 10005 id = 428 }
      name   = "2. Mountaineers"
      type   = bergsjaeger
      model  = 1
	  strength = 50
    }
  }
  landunit =
  { id       = { type = 10700 id = 429 }
    location = 1897
    name     = "15th Border Guards"
    division =
    { id     = { type = 10700 id = 430 }
      name   = "al-Mushati al-30i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 431 }
      name   = "al-Mushati al-31i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 432 }
      name   = "al-Mushati al-32i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  landunit =
  { id       = { type = 10700 id = 433 }
    location = 1734
    name     = "Pearl Harbour Garrison"
    division =
    { id     = { type = 10700 id = 434 }
      name   = "Pearl Garrison"
      type   = garrison
      model  = 0
	  strength = 35
	  locked = yes
    }
  }
  landunit =
  { id       = { type = 10700 id = 435 }
    location = 1898
    name     = "16th Border Guards"
    division =
    { id     = { type = 10700 id = 436 }
      name   = "al-Mushati al-36i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 437 }
      name   = "al-Mushati al-37i"
      type = infantry
	  strength = 40
	  model = 1
    }
    division =
    { id     = { type = 10700 id = 438 }
      name   = "al-Mushati al-38i"
      type = infantry
	  strength = 40
	  model = 1
    }
  }
  #Air Force
  airunit =
  { location = 1922
    base     = 1922
    id       = { type = 10500 id = 745 }
    name     = "Interceptor Squadron"
    division =
    { id     = { type = 10500 id = 680 }
      name   = "1. MAF Fighter Group"
      type   = interceptor
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 681 }
      name   = "2. MAF Fighter Group"
      type   = interceptor
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 682 }
      name   = "3. MAF Fighter Group"
      type   = interceptor
      model  = 1
    }
  }
  airunit =
  { location = 1896
    base     = 1896
    id       = { type = 10500 id = 683 }
    name     = "Bomber Squadron"
    division =
    { id     = { type = 10500 id = 684 }
      name   = "1. MAF Strategic Bomb Group"
      type   = strategic_bomber
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 685 }
      name   = "2. MAF Strategic Bomb Group"
      type   = strategic_bomber
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 686 }
      name   = "1. MAF Tactical Bomb Group"
      type   = tactical_bomber
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 687 }
      name   = "2. MAF Tactical Bomb Group"
      type   = tactical_bomber
      model  = 1
    }
  }
  #Navy
  navalunit =
  { id       = { type = 10500 id = 688 }
    name     = "Transport Fleet"
    location = 1928
    base     = 1928
    division =
    { id     = { type = 10500 id = 689 }
      name   = "Ustul al-Hamli al-1i"
      type   = transport
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 690 }
      name   = "Ustul al-Hamli al-2i"
      type   = transport
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 691 }
      name   = "Ustul al-Hamli al-3i"
      type   = transport
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 692 }
      name   = "Ustul al-Hamli al-4i"
      type   = transport
      model  = 0
    }
  }
  navalunit =
  { id       = { type = 10500 id = 693 }
    name     = "Submarine Fleet"
    location = 1966
    base     = 1966
    division =
    { id     = { type = 10500 id = 694 }
      name   = "Ustul al-Ghawwasati al-1i"
      type   = submarine
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 695 }
      name   = "Ustul al-Ghawwasati al-2i"
      type   = submarine
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 696 }
      name   = "Ustul al-Ghawwasati al-3i"
      type   = submarine
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 697 }
      name   = "Ustul al-Ghawwasati al-4i"
      type   = submarine
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 698 }
      name   = "Ustul al-Ghawwasati al-5i"
      type   = submarine
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 699 }
      name   = "Ustul al-Ghawwasati al-6i"
      type   = submarine
      model  = 2
    }
  }
  navalunit =
  { id       = { type = 10500 id = 746 }
    name     = "Cape Horn Fleet"
    location = 880
    base     = 880
    division =
    { id     = { type = 10500 id = 804 }
      name   = "MSS Limayakla"
      type   = battleship
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 805 }
      name   = "MSS Lqizt"
      type   = escort_carrier
      model  = 1
      extra  = naval_torpedoes_s
      brigade_model = 2
    }
    division =
    { id     = { type = 10500 id = 747 }
      name   = "MSS Iyis"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 748 }
      name   = "MSS Tagmart"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 749 }
      name   = "MSS Ibruri"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 750 }
      name   = "MSS Tazmat"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 751 }
      name   = "Flottille al-9i"
      type   = destroyer
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 752 }
      name   = "Flottille al-12i"
      type   = destroyer
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 753 }
      name   = "Flottille al-13i"
      type   = destroyer
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 754 }
      name   = "Flottille al-14i"
      type   = destroyer
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 755 }
      name   = "MSS Selaw"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 756 }
      name   = "MSS Hawis"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 757 }
      name   = "MSS Irzzi"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 758 }
      name   = "MSS Tizwit"
      type   = light_cruiser
      model  = 1
    }
  }
  navalunit =
  { id       = { type = 10500 id = 763 }
    name     = "South Pacific Fleet"
    location = 1972
    base     = 1972
    division =
    { id     = { type = 10500 id = 764 }
      name   = "MSS Mazula"
      type   = carrier
      model  = 1
      extra  = cag
      brigade_model = 1
    }
    division =
    { id     = { type = 10500 id = 765 }
      name   = "MSS Anqar"
      type   = carrier
      model  = 1
      extra  = cag
      brigade_model = 1
    }
    division =
    { id     = { type = 10500 id = 766 }
      name   = "MSS Qelluq"
      type   = battleship
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 767 }
      name   = "MSS Xitir"
      type   = battleship
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 768 }
      name   = "MSS Ninag"
      type   = battleship
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 769 }
      name   = "MSS Salem"
      type   = battleship
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 770 }
      name   = "MSS Safiya"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 771 }
      name   = "MSS Mahmoud"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 772 }
      name   = "MSS Azlim"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 773 }
      name   = "MSS Rzris"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 774 }
      name   = "MSS Tazlakt"
      type   = light_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 775 }
      name   = "MSS Limudir"
      type   = light_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 776 }
      name   = "Flottille al-2i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 777 }
      name   = "Flottille al-3i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 778 }
      name   = "Flottille al-4i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 779 }
      name   = "Flottille al-1i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 780 }
      name   = "Flottille al-10i"
      type   = destroyer
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 781 }
      name   = "Flottille al-11i"
      type   = destroyer
      model  = 1
    }
  }
  navalunit =
  { id       = { type = 10500 id = 782 }
    name     = "Gulf Fleet"
    location = 1922
    base     = 1922
    division =
    { id     = { type = 10500 id = 783 }
      name   = "MSS Dafi"
      type   = escort_carrier
      model  = 0
      extra  = naval_torpedoes_s
      brigade_model = 2
    }
    division =
    { id     = { type = 10500 id = 784 }
      name   = "MSS Muz"
      type   = battleship
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 785 }
      name   = "MSS Tadda"
      type   = battleship
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 786 }
      name   = "MSS Xatar"
      type   = battleship
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 787 }
      name   = "MSS Bizri"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 788 }
      name   = "MSS Amzi"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 789 }
      name   = "MSS Hakim"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 790 }
      name   = "MSS Uzum"
      type   = heavy_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 791 }
      name   = "MSS Hissi"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 792 }
      name   = "MSS Azur"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 793 }
      name   = "MSS Izur"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 794 }
      name   = "MSS Jezber"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 795 }
      name   = "MSS Berber"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 796 }
      name   = "MSS Xadim"
      type   = light_cruiser
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 797 }
      name   = "Flottille al-5i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 798 }
      name   = "Flottille al-6i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 799 }
      name   = "Flottille al-7i"
      type   = destroyer
      model  = 0
    }
    division =
    { id     = { type = 10500 id = 800 }
      name   = "Flottille al-8i"
      type   = destroyer
      model  = 0
    }
  }
  navalunit =
  { id       = { type = 10500 id = 801 }
    name     = "Pacific Fleet"
    location = 1734
    base     = 1734
    division =
    { id     = { type = 10500 id = 802 }
      name   = "MSS Siwet"
      type   = carrier
      model  = 2
      extra  = cag
      brigade_model = 2
    }
    division =
    { id     = { type = 10500 id = 803 }
      name   = "MSS Jamhuria"
      type   = carrier
      model  = 2
      extra  = cag
      brigade_model = 2
    }
    division =
    { id     = { type = 10500 id = 806 }
      name   = "MSS Haddid"
      type   = battleship
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 807 }
      name   = "MSS Hital"
      type   = battleship
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 808 }
      name   = "MSS Kiti"
      type   = heavy_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 809 }
      name   = "MSS Hitarm"
      type   = heavy_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 810 }
      name   = "MSS Lamazut"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 811 }
      name   = "MSS Hidu"
      type   = heavy_cruiser
      model  = 1
    }
    division =
    { id     = { type = 10500 id = 812 }
      name   = "MSS Zadig"
      type   = heavy_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 813 }
      name   = "MSS Leqanun"
      type   = light_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 814 }
      name   = "MSS Jigwa"
      type   = light_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 815 }
      name   = "MSS Linit"
      type   = light_cruiser
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 816 }
      name   = "Flottille al-15i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 817 }
      name   = "Flottille al-16i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 818 }
      name   = "Flottille al-17i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 819 }
      name   = "Flottille al-18i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 820 }
      name   = "Flottille al-19i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 821 }
      name   = "Flottille al-20i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 822 }
      name   = "Flottille al-21i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 823 }
      name   = "Flottille al-22i"
      type   = destroyer
      model  = 2
    }
    division =
    { id     = { type = 10500 id = 824 }
      name   = "Flottille al-23i"
      type   = destroyer
      model  = 2
    }
  }
}
